/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Rootly API
 * OpenAPI spec version: 0.1.0
 */

export type CreateTagBodyColor =
  (typeof CreateTagBodyColor)[keyof typeof CreateTagBodyColor]

export const CreateTagBodyColor = {
  blue: 'blue',
  green: 'green',
  orange: 'orange',
  purple: 'purple',
  red: 'red',
  yellow: 'yellow',
} as const
