/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Rootly API
 * OpenAPI spec version: 0.1.0
 */
import type { CreateItemBodyType } from './createItemBodyType'

export type CreateItemBody = {
  title: string
  folderId?: string
  workspaceId: string
  type: CreateItemBodyType
  content?: string
}
