/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Rootly API
 * OpenAPI spec version: 0.1.0
 */

export type GetActivityLogsResourceType = typeof GetActivityLogsResourceType[keyof typeof GetActivityLogsResourceType];


export const GetActivityLogsResourceType = {
  folder: 'folder',
  item: 'item',
  member: 'member',
  workspace: 'workspace',
} as const;
