/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Rootly API
 * OpenAPI spec version: 0.1.0
 */

/**
 * @nullable
 */
export type GetActivityLogs200ActivityLogsItemMetadata = {
  before?: {[key: string]: unknown};
  after?: {[key: string]: unknown};
} | null;
