/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Rootly API
 * OpenAPI spec version: 0.1.0
 */
import type { GetActivityLogsResourceType } from './getActivityLogsResourceType';

export type GetActivityLogsParams = {
resourceId?: string;
resourceType?: GetActivityLogsResourceType;
};
