/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Rootly API
 * OpenAPI spec version: 0.1.0
 */

export type GetActivityLogs200ActivityLogsItemAction = typeof GetActivityLogs200ActivityLogsItemAction[keyof typeof GetActivityLogs200ActivityLogsItemAction];


export const GetActivityLogs200ActivityLogsItemAction = {
  folder_created: 'folder_created',
  folder_renamed: 'folder_renamed',
  folder_deleted: 'folder_deleted',
  item_created: 'item_created',
  item_updated: 'item_updated',
  item_archived: 'item_archived',
  item_restored: 'item_restored',
  item_deleted: 'item_deleted',
  member_invited: 'member_invited',
  member_joined: 'member_joined',
  member_role_changed: 'member_role_changed',
  member_removed: 'member_removed',
  workspace_renamed: 'workspace_renamed',
  role_created: 'role_created',
  role_deleted: 'role_deleted',
  role_permissions_changed: 'role_permissions_changed',
} as const;
