/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Rootly API
 * OpenAPI spec version: 0.1.0
 */
import type { GetActivityLogs200ActivityLogsItem } from './getActivityLogs200ActivityLogsItem';

export type GetActivityLogs200 = {
  activityLogs: GetActivityLogs200ActivityLogsItem[];
};
