/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Rootly API
 * OpenAPI spec version: 0.1.0
 */
import type { GetItems200ItemsItemType } from './getItems200ItemsItemType'

export type GetItems200ItemsItem = {
  id: string
  title: string
  type: GetItems200ItemsItemType
  /** @nullable */
  content: string | null
  workspaceId: string
  /** @nullable */
  folderId: string | null
  tagIds: string[]
  createdAt: string
  updatedAt: string
}
