/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Rootly API
 * OpenAPI spec version: 0.1.0
 */

export type GetItems200ItemsItemType =
  (typeof GetItems200ItemsItemType)[keyof typeof GetItems200ItemsItemType]

export const GetItems200ItemsItemType = {
  link: 'link',
  document: 'document',
  text: 'text',
  secret: 'secret',
} as const
