/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Rootly API
 * OpenAPI spec version: 0.1.0
 */
import type { GetItems200ItemsItem } from './getItems200ItemsItem'

export type GetItems200 = {
  items: GetItems200ItemsItem[]
}
