/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Rootly API
 * OpenAPI spec version: 0.1.0
 */

export type GetMyWorkspacePermissions200PermissionsItemAction = typeof GetMyWorkspacePermissions200PermissionsItemAction[keyof typeof GetMyWorkspacePermissions200PermissionsItemAction];


export const GetMyWorkspacePermissions200PermissionsItemAction = {
  create: 'create',
  read: 'read',
  update: 'update',
  delete: 'delete',
  invite: 'invite',
  all: 'all',
} as const;
