/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Rootly API
 * OpenAPI spec version: 0.1.0
 */

export type GetMyWorkspacePermissions200PermissionsItemResource = typeof GetMyWorkspacePermissions200PermissionsItemResource[keyof typeof GetMyWorkspacePermissions200PermissionsItemResource];


export const GetMyWorkspacePermissions200PermissionsItemResource = {
  workspace: 'workspace',
  folder: 'folder',
  item: 'item',
  tag: 'tag',
  member: 'member',
  role: 'role',
} as const;
