/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Rootly API
 * OpenAPI spec version: 0.1.0
 */
import type { GetMyWorkspacePermissions200PermissionsItem } from './getMyWorkspacePermissions200PermissionsItem'

export type GetMyWorkspacePermissions200 = {
  permissions: GetMyWorkspacePermissions200PermissionsItem[]
}
