/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Rootly API
 * OpenAPI spec version: 0.1.0
 */
import type { GetNotifications200NotificationsItemMetadata } from './getNotifications200NotificationsItemMetadata'

export type GetNotifications200NotificationsItem = {
  id: string
  title: string
  content: string
  metadata: GetNotifications200NotificationsItemMetadata
  /** @nullable */
  readAt: string | null
  createdAt: string
}
