/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Rootly API
 * OpenAPI spec version: 0.1.0
 */
import type { GetNotifications200NotificationsItem } from './getNotifications200NotificationsItem';

export type GetNotifications200 = {
  notifications: GetNotifications200NotificationsItem[];
};
