/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Rootly API
 * OpenAPI spec version: 0.1.0
 */

export type GetRolePermissions200PermissionsItemResource = typeof GetRolePermissions200PermissionsItemResource[keyof typeof GetRolePermissions200PermissionsItemResource];


export const GetRolePermissions200PermissionsItemResource = {
  workspace: 'workspace',
  folder: 'folder',
  item: 'item',
  member: 'member',
  role: 'role',
  activity: 'activity',
} as const;
