/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Rootly API
 * OpenAPI spec version: 0.1.0
 */

export type GetRolePermissions200PermissionsItemAction =
  (typeof GetRolePermissions200PermissionsItemAction)[keyof typeof GetRolePermissions200PermissionsItemAction]

export const GetRolePermissions200PermissionsItemAction = {
  read: 'read',
  create: 'create',
  update: 'update',
  delete: 'delete',
  invite: 'invite',
  all: 'all',
} as const
