/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Rootly API
 * OpenAPI spec version: 0.1.0
 */
import type { GetRolePermissions200PermissionsItem } from './getRolePermissions200PermissionsItem'

export type GetRolePermissions200 = {
  permissions: GetRolePermissions200PermissionsItem[]
}
