/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Rootly API
 * OpenAPI spec version: 0.1.0
 */

export type GetTagsParams = {
workspaceId: string;
cursor?: string;
/**
 * @minimum 1
 * @maximum 1000
 */
limit?: number;
};
