/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Rootly API
 * OpenAPI spec version: 0.1.0
 */

export type GetTags200TagsItemColor = typeof GetTags200TagsItemColor[keyof typeof GetTags200TagsItemColor];


export const GetTags200TagsItemColor = {
  blue: 'blue',
  green: 'green',
  orange: 'orange',
  purple: 'purple',
  red: 'red',
  yellow: 'yellow',
} as const;
