/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Rootly API
 * OpenAPI spec version: 0.1.0
 */

export type GetWorkspaces200WorkspacesItem = {
  id: string
  name: string
  userId: string
  createdAt: string
  updatedAt: string
}
