/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Rootly API
 * OpenAPI spec version: 0.1.0
 */
import type { GetWorkspace200Workspace } from './getWorkspace200Workspace'

export type GetWorkspace200 = {
  workspace: GetWorkspace200Workspace
}
