/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Rootly API
 * OpenAPI spec version: 0.1.0
 */
import type { GetWorkspaces200WorkspacesItem } from './getWorkspaces200WorkspacesItem'

export type GetWorkspaces200 = {
  workspaces: GetWorkspaces200WorkspacesItem[]
}
