/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Rootly API
 * OpenAPI spec version: 0.1.0
 */
import type { GetWorkspaceMembers200MembersItem } from './getWorkspaceMembers200MembersItem'

export type GetWorkspaceMembers200 = {
  members: GetWorkspaceMembers200MembersItem[]
}
