/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Rootly API
 * OpenAPI spec version: 0.1.0
 */

/**
 * @nullable
 */
export type Logout204 = typeof Logout204[keyof typeof Logout204] | null;


export const Logout204 = {
} as const;
