/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Rootly API
 * OpenAPI spec version: 0.1.0
 */

export type SetRolePermissionsBodyPermissionsItemAction =
  (typeof SetRolePermissionsBodyPermissionsItemAction)[keyof typeof SetRolePermissionsBodyPermissionsItemAction]

export const SetRolePermissionsBodyPermissionsItemAction = {
  read: 'read',
  create: 'create',
  update: 'update',
  delete: 'delete',
  invite: 'invite',
  all: 'all',
} as const
