/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Rootly API
 * OpenAPI spec version: 0.1.0
 */
import type { SetRolePermissionsBodyPermissionsItemAction } from './setRolePermissionsBodyPermissionsItemAction';
import type { SetRolePermissionsBodyPermissionsItemResource } from './setRolePermissionsBodyPermissionsItemResource';

export type SetRolePermissionsBodyPermissionsItem = {
  resource: SetRolePermissionsBodyPermissionsItemResource;
  action: SetRolePermissionsBodyPermissionsItemAction;
};
