/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Rootly API
 * OpenAPI spec version: 0.1.0
 */

export type SetRolePermissionsBodyPermissionsItemResource =
  (typeof SetRolePermissionsBodyPermissionsItemResource)[keyof typeof SetRolePermissionsBodyPermissionsItemResource]

export const SetRolePermissionsBodyPermissionsItemResource = {
  workspace: 'workspace',
  folder: 'folder',
  item: 'item',
  tag: 'tag',
  member: 'member',
  role: 'role',
} as const
