/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Rootly API
 * OpenAPI spec version: 0.1.0
 */

/**
 * @nullable
 */
export type UpdateProfile204 = typeof UpdateProfile204[keyof typeof UpdateProfile204] | null;


export const UpdateProfile204 = {
} as const;
