/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Rootly API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  CreateFolder201,
  CreateFolder400,
  CreateFolder401,
  CreateFolder409,
  CreateFolder500,
  CreateFolderBody,
  DeleteFolder401,
  DeleteFolder404,
  DeleteFolder409,
  DeleteFolder500,
  GetFolders200,
  GetFolders401,
  GetFolders500,
  GetFoldersParams,
  RenameFolder400,
  RenameFolder401,
  RenameFolder404,
  RenameFolder409,
  RenameFolder500,
  RenameFolderBody,
  ResolveFolderPath200,
  ResolveFolderPath401,
  ResolveFolderPath404,
  ResolveFolderPath500,
  ResolveFolderPathParams
} from '../model';

import { fetchWithAuth } from '../../lib/fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Create a new folder
 * @summary Create Folder
 */
export type createFolderResponse201 = {
  data: CreateFolder201
  status: 201
}

export type createFolderResponse400 = {
  data: CreateFolder400
  status: 400
}

export type createFolderResponse401 = {
  data: CreateFolder401
  status: 401
}

export type createFolderResponse409 = {
  data: CreateFolder409
  status: 409
}

export type createFolderResponse500 = {
  data: CreateFolder500
  status: 500
}

export type createFolderResponseSuccess = (createFolderResponse201) & {
  headers: Headers;
};
export type createFolderResponseError = (createFolderResponse400 | createFolderResponse401 | createFolderResponse409 | createFolderResponse500) & {
  headers: Headers;
};

export type createFolderResponse = (createFolderResponseSuccess | createFolderResponseError)

export const getCreateFolderUrl = () => {


  

  return `http://localhost:3333/api/folders`
}

export const createFolder = async (createFolderBody: CreateFolderBody, options?: RequestInit): Promise<createFolderResponse> => {
  
  return fetchWithAuth<createFolderResponse>(getCreateFolderUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createFolderBody,)
  }
);}
  



export const getCreateFolderMutationOptions = <TError = CreateFolder400 | CreateFolder401 | CreateFolder409 | CreateFolder500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createFolder>>, TError,{data: CreateFolderBody}, TContext>, request?: SecondParameter<typeof fetchWithAuth>}
): UseMutationOptions<Awaited<ReturnType<typeof createFolder>>, TError,{data: CreateFolderBody}, TContext> => {

const mutationKey = ['createFolder'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createFolder>>, {data: CreateFolderBody}> = (props) => {
          const {data} = props ?? {};

          return  createFolder(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateFolderMutationResult = NonNullable<Awaited<ReturnType<typeof createFolder>>>
    export type CreateFolderMutationBody = CreateFolderBody
    export type CreateFolderMutationError = CreateFolder400 | CreateFolder401 | CreateFolder409 | CreateFolder500

    /**
 * @summary Create Folder
 */
export const useCreateFolder = <TError = CreateFolder400 | CreateFolder401 | CreateFolder409 | CreateFolder500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createFolder>>, TError,{data: CreateFolderBody}, TContext>, request?: SecondParameter<typeof fetchWithAuth>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createFolder>>,
        TError,
        {data: CreateFolderBody},
        TContext
      > => {
      return useMutation(getCreateFolderMutationOptions(options), queryClient);
    }
    /**
 * List folders. Optionally filter by parentId or workspaceId.
 * @summary Get Folders
 */
export type getFoldersResponse200 = {
  data: GetFolders200
  status: 200
}

export type getFoldersResponse401 = {
  data: GetFolders401
  status: 401
}

export type getFoldersResponse500 = {
  data: GetFolders500
  status: 500
}

export type getFoldersResponseSuccess = (getFoldersResponse200) & {
  headers: Headers;
};
export type getFoldersResponseError = (getFoldersResponse401 | getFoldersResponse500) & {
  headers: Headers;
};

export type getFoldersResponse = (getFoldersResponseSuccess | getFoldersResponseError)

export const getGetFoldersUrl = (params?: GetFoldersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3333/api/folders?${stringifiedParams}` : `http://localhost:3333/api/folders`
}

export const getFolders = async (params?: GetFoldersParams, options?: RequestInit): Promise<getFoldersResponse> => {
  
  return fetchWithAuth<getFoldersResponse>(getGetFoldersUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getGetFoldersQueryKey = (params?: GetFoldersParams,) => {
    return [
    'http:','localhost:3333','api','folders', ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetFoldersQueryOptions = <TData = Awaited<ReturnType<typeof getFolders>>, TError = GetFolders401 | GetFolders500>(params?: GetFoldersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFolders>>, TError, TData>>, request?: SecondParameter<typeof fetchWithAuth>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFoldersQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFolders>>> = ({ signal }) => getFolders(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFolders>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFoldersQueryResult = NonNullable<Awaited<ReturnType<typeof getFolders>>>
export type GetFoldersQueryError = GetFolders401 | GetFolders500


export function useGetFolders<TData = Awaited<ReturnType<typeof getFolders>>, TError = GetFolders401 | GetFolders500>(
 params: undefined |  GetFoldersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFolders>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFolders>>,
          TError,
          Awaited<ReturnType<typeof getFolders>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetchWithAuth>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFolders<TData = Awaited<ReturnType<typeof getFolders>>, TError = GetFolders401 | GetFolders500>(
 params?: GetFoldersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFolders>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFolders>>,
          TError,
          Awaited<ReturnType<typeof getFolders>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetchWithAuth>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFolders<TData = Awaited<ReturnType<typeof getFolders>>, TError = GetFolders401 | GetFolders500>(
 params?: GetFoldersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFolders>>, TError, TData>>, request?: SecondParameter<typeof fetchWithAuth>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Folders
 */

export function useGetFolders<TData = Awaited<ReturnType<typeof getFolders>>, TError = GetFolders401 | GetFolders500>(
 params?: GetFoldersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFolders>>, TError, TData>>, request?: SecondParameter<typeof fetchWithAuth>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetFoldersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetFoldersSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getFolders>>, TError = GetFolders401 | GetFolders500>(params?: GetFoldersParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getFolders>>, TError, TData>>, request?: SecondParameter<typeof fetchWithAuth>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFoldersQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFolders>>> = ({ signal }) => getFolders(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getFolders>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFoldersSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getFolders>>>
export type GetFoldersSuspenseQueryError = GetFolders401 | GetFolders500


export function useGetFoldersSuspense<TData = Awaited<ReturnType<typeof getFolders>>, TError = GetFolders401 | GetFolders500>(
 params: undefined |  GetFoldersParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getFolders>>, TError, TData>>, request?: SecondParameter<typeof fetchWithAuth>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFoldersSuspense<TData = Awaited<ReturnType<typeof getFolders>>, TError = GetFolders401 | GetFolders500>(
 params?: GetFoldersParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getFolders>>, TError, TData>>, request?: SecondParameter<typeof fetchWithAuth>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFoldersSuspense<TData = Awaited<ReturnType<typeof getFolders>>, TError = GetFolders401 | GetFolders500>(
 params?: GetFoldersParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getFolders>>, TError, TData>>, request?: SecondParameter<typeof fetchWithAuth>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Folders
 */

export function useGetFoldersSuspense<TData = Awaited<ReturnType<typeof getFolders>>, TError = GetFolders401 | GetFolders500>(
 params?: GetFoldersParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getFolders>>, TError, TData>>, request?: SecondParameter<typeof fetchWithAuth>}
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetFoldersSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Resolve a folder path (list of ids separated by /) into the ordered chain of folder names. Validates that every id belongs to the workspace and that each folder is a child of the previous.
 * @summary Resolve Folder Path
 */
export type resolveFolderPathResponse200 = {
  data: ResolveFolderPath200
  status: 200
}

export type resolveFolderPathResponse401 = {
  data: ResolveFolderPath401
  status: 401
}

export type resolveFolderPathResponse404 = {
  data: ResolveFolderPath404
  status: 404
}

export type resolveFolderPathResponse500 = {
  data: ResolveFolderPath500
  status: 500
}

export type resolveFolderPathResponseSuccess = (resolveFolderPathResponse200) & {
  headers: Headers;
};
export type resolveFolderPathResponseError = (resolveFolderPathResponse401 | resolveFolderPathResponse404 | resolveFolderPathResponse500) & {
  headers: Headers;
};

export type resolveFolderPathResponse = (resolveFolderPathResponseSuccess | resolveFolderPathResponseError)

export const getResolveFolderPathUrl = (params: ResolveFolderPathParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3333/api/folders/resolve-path?${stringifiedParams}` : `http://localhost:3333/api/folders/resolve-path`
}

export const resolveFolderPath = async (params: ResolveFolderPathParams, options?: RequestInit): Promise<resolveFolderPathResponse> => {
  
  return fetchWithAuth<resolveFolderPathResponse>(getResolveFolderPathUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getResolveFolderPathQueryKey = (params?: ResolveFolderPathParams,) => {
    return [
    'http:','localhost:3333','api','folders','resolve-path', ...(params ? [params] : [])
    ] as const;
    }

    
export const getResolveFolderPathQueryOptions = <TData = Awaited<ReturnType<typeof resolveFolderPath>>, TError = ResolveFolderPath401 | ResolveFolderPath404 | ResolveFolderPath500>(params: ResolveFolderPathParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resolveFolderPath>>, TError, TData>>, request?: SecondParameter<typeof fetchWithAuth>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getResolveFolderPathQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof resolveFolderPath>>> = ({ signal }) => resolveFolderPath(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof resolveFolderPath>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ResolveFolderPathQueryResult = NonNullable<Awaited<ReturnType<typeof resolveFolderPath>>>
export type ResolveFolderPathQueryError = ResolveFolderPath401 | ResolveFolderPath404 | ResolveFolderPath500


export function useResolveFolderPath<TData = Awaited<ReturnType<typeof resolveFolderPath>>, TError = ResolveFolderPath401 | ResolveFolderPath404 | ResolveFolderPath500>(
 params: ResolveFolderPathParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof resolveFolderPath>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof resolveFolderPath>>,
          TError,
          Awaited<ReturnType<typeof resolveFolderPath>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetchWithAuth>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useResolveFolderPath<TData = Awaited<ReturnType<typeof resolveFolderPath>>, TError = ResolveFolderPath401 | ResolveFolderPath404 | ResolveFolderPath500>(
 params: ResolveFolderPathParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resolveFolderPath>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof resolveFolderPath>>,
          TError,
          Awaited<ReturnType<typeof resolveFolderPath>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetchWithAuth>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useResolveFolderPath<TData = Awaited<ReturnType<typeof resolveFolderPath>>, TError = ResolveFolderPath401 | ResolveFolderPath404 | ResolveFolderPath500>(
 params: ResolveFolderPathParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resolveFolderPath>>, TError, TData>>, request?: SecondParameter<typeof fetchWithAuth>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Resolve Folder Path
 */

export function useResolveFolderPath<TData = Awaited<ReturnType<typeof resolveFolderPath>>, TError = ResolveFolderPath401 | ResolveFolderPath404 | ResolveFolderPath500>(
 params: ResolveFolderPathParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resolveFolderPath>>, TError, TData>>, request?: SecondParameter<typeof fetchWithAuth>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getResolveFolderPathQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getResolveFolderPathSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof resolveFolderPath>>, TError = ResolveFolderPath401 | ResolveFolderPath404 | ResolveFolderPath500>(params: ResolveFolderPathParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof resolveFolderPath>>, TError, TData>>, request?: SecondParameter<typeof fetchWithAuth>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getResolveFolderPathQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof resolveFolderPath>>> = ({ signal }) => resolveFolderPath(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof resolveFolderPath>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ResolveFolderPathSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof resolveFolderPath>>>
export type ResolveFolderPathSuspenseQueryError = ResolveFolderPath401 | ResolveFolderPath404 | ResolveFolderPath500


export function useResolveFolderPathSuspense<TData = Awaited<ReturnType<typeof resolveFolderPath>>, TError = ResolveFolderPath401 | ResolveFolderPath404 | ResolveFolderPath500>(
 params: ResolveFolderPathParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof resolveFolderPath>>, TError, TData>>, request?: SecondParameter<typeof fetchWithAuth>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useResolveFolderPathSuspense<TData = Awaited<ReturnType<typeof resolveFolderPath>>, TError = ResolveFolderPath401 | ResolveFolderPath404 | ResolveFolderPath500>(
 params: ResolveFolderPathParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof resolveFolderPath>>, TError, TData>>, request?: SecondParameter<typeof fetchWithAuth>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useResolveFolderPathSuspense<TData = Awaited<ReturnType<typeof resolveFolderPath>>, TError = ResolveFolderPath401 | ResolveFolderPath404 | ResolveFolderPath500>(
 params: ResolveFolderPathParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof resolveFolderPath>>, TError, TData>>, request?: SecondParameter<typeof fetchWithAuth>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Resolve Folder Path
 */

export function useResolveFolderPathSuspense<TData = Awaited<ReturnType<typeof resolveFolderPath>>, TError = ResolveFolderPath401 | ResolveFolderPath404 | ResolveFolderPath500>(
 params: ResolveFolderPathParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof resolveFolderPath>>, TError, TData>>, request?: SecondParameter<typeof fetchWithAuth>}
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getResolveFolderPathSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Permanently delete an empty folder
 * @summary Delete Folder
 */
export type deleteFolderResponse204 = {
  data: void
  status: 204
}

export type deleteFolderResponse401 = {
  data: DeleteFolder401
  status: 401
}

export type deleteFolderResponse404 = {
  data: DeleteFolder404
  status: 404
}

export type deleteFolderResponse409 = {
  data: DeleteFolder409
  status: 409
}

export type deleteFolderResponse500 = {
  data: DeleteFolder500
  status: 500
}

export type deleteFolderResponseSuccess = (deleteFolderResponse204) & {
  headers: Headers;
};
export type deleteFolderResponseError = (deleteFolderResponse401 | deleteFolderResponse404 | deleteFolderResponse409 | deleteFolderResponse500) & {
  headers: Headers;
};

export type deleteFolderResponse = (deleteFolderResponseSuccess | deleteFolderResponseError)

export const getDeleteFolderUrl = (folderId: string,) => {


  

  return `http://localhost:3333/api/folders/${folderId}`
}

export const deleteFolder = async (folderId: string, options?: RequestInit): Promise<deleteFolderResponse> => {
  
  return fetchWithAuth<deleteFolderResponse>(getDeleteFolderUrl(folderId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  



export const getDeleteFolderMutationOptions = <TError = DeleteFolder401 | DeleteFolder404 | DeleteFolder409 | DeleteFolder500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteFolder>>, TError,{folderId: string}, TContext>, request?: SecondParameter<typeof fetchWithAuth>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteFolder>>, TError,{folderId: string}, TContext> => {

const mutationKey = ['deleteFolder'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteFolder>>, {folderId: string}> = (props) => {
          const {folderId} = props ?? {};

          return  deleteFolder(folderId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteFolderMutationResult = NonNullable<Awaited<ReturnType<typeof deleteFolder>>>
    
    export type DeleteFolderMutationError = DeleteFolder401 | DeleteFolder404 | DeleteFolder409 | DeleteFolder500

    /**
 * @summary Delete Folder
 */
export const useDeleteFolder = <TError = DeleteFolder401 | DeleteFolder404 | DeleteFolder409 | DeleteFolder500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteFolder>>, TError,{folderId: string}, TContext>, request?: SecondParameter<typeof fetchWithAuth>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteFolder>>,
        TError,
        {folderId: string},
        TContext
      > => {
      return useMutation(getDeleteFolderMutationOptions(options), queryClient);
    }
    /**
 * Rename a folder.
 * @summary Rename Folder
 */
export type renameFolderResponse204 = {
  data: void
  status: 204
}

export type renameFolderResponse400 = {
  data: RenameFolder400
  status: 400
}

export type renameFolderResponse401 = {
  data: RenameFolder401
  status: 401
}

export type renameFolderResponse404 = {
  data: RenameFolder404
  status: 404
}

export type renameFolderResponse409 = {
  data: RenameFolder409
  status: 409
}

export type renameFolderResponse500 = {
  data: RenameFolder500
  status: 500
}

export type renameFolderResponseSuccess = (renameFolderResponse204) & {
  headers: Headers;
};
export type renameFolderResponseError = (renameFolderResponse400 | renameFolderResponse401 | renameFolderResponse404 | renameFolderResponse409 | renameFolderResponse500) & {
  headers: Headers;
};

export type renameFolderResponse = (renameFolderResponseSuccess | renameFolderResponseError)

export const getRenameFolderUrl = (folderId: string,) => {


  

  return `http://localhost:3333/api/folders/${folderId}`
}

export const renameFolder = async (folderId: string,
    renameFolderBody: RenameFolderBody, options?: RequestInit): Promise<renameFolderResponse> => {
  
  return fetchWithAuth<renameFolderResponse>(getRenameFolderUrl(folderId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      renameFolderBody,)
  }
);}
  



export const getRenameFolderMutationOptions = <TError = RenameFolder400 | RenameFolder401 | RenameFolder404 | RenameFolder409 | RenameFolder500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof renameFolder>>, TError,{folderId: string;data: RenameFolderBody}, TContext>, request?: SecondParameter<typeof fetchWithAuth>}
): UseMutationOptions<Awaited<ReturnType<typeof renameFolder>>, TError,{folderId: string;data: RenameFolderBody}, TContext> => {

const mutationKey = ['renameFolder'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof renameFolder>>, {folderId: string;data: RenameFolderBody}> = (props) => {
          const {folderId,data} = props ?? {};

          return  renameFolder(folderId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RenameFolderMutationResult = NonNullable<Awaited<ReturnType<typeof renameFolder>>>
    export type RenameFolderMutationBody = RenameFolderBody
    export type RenameFolderMutationError = RenameFolder400 | RenameFolder401 | RenameFolder404 | RenameFolder409 | RenameFolder500

    /**
 * @summary Rename Folder
 */
export const useRenameFolder = <TError = RenameFolder400 | RenameFolder401 | RenameFolder404 | RenameFolder409 | RenameFolder500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof renameFolder>>, TError,{folderId: string;data: RenameFolderBody}, TContext>, request?: SecondParameter<typeof fetchWithAuth>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof renameFolder>>,
        TError,
        {folderId: string;data: RenameFolderBody},
        TContext
      > => {
      return useMutation(getRenameFolderMutationOptions(options), queryClient);
    }
    