/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Rootly API
 * OpenAPI spec version: 0.1.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query'
import { useMutation, useQuery, useSuspenseQuery } from '@tanstack/react-query'
import { fetchWithAuth } from '../../shared/lib/fetch'
import { QUERY_KEYS } from '../keys'
import type {
  AssignTagToFolder401,
  AssignTagToFolder404,
  AssignTagToFolder500,
  CreateFolder201,
  CreateFolder400,
  CreateFolder401,
  CreateFolder409,
  CreateFolder500,
  CreateFolderBody,
  GetFolders200,
  GetFolders401,
  GetFolders500,
  GetFoldersParams,
} from '../model'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Create a new folder
 * @summary Create Folder
 */
export type createFolderResponse201 = {
  data: CreateFolder201
  status: 201
}

export type createFolderResponse400 = {
  data: CreateFolder400
  status: 400
}

export type createFolderResponse401 = {
  data: CreateFolder401
  status: 401
}

export type createFolderResponse409 = {
  data: CreateFolder409
  status: 409
}

export type createFolderResponse500 = {
  data: CreateFolder500
  status: 500
}

export type createFolderResponseSuccess = createFolderResponse201 & {
  headers: Headers
}
export type createFolderResponseError = (
  | createFolderResponse400
  | createFolderResponse401
  | createFolderResponse409
  | createFolderResponse500
) & {
  headers: Headers
}

export type createFolderResponse =
  | createFolderResponseSuccess
  | createFolderResponseError

export const getCreateFolderUrl = () => {
  return `http://localhost:3333/api/folders`
}

export const createFolder = async (
  createFolderBody: CreateFolderBody,
  options?: RequestInit,
): Promise<createFolderResponse> => {
  return fetchWithAuth<createFolderResponse>(getCreateFolderUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createFolderBody),
  })
}

export const getCreateFolderMutationOptions = <
  TError =
    | CreateFolder400
    | CreateFolder401
    | CreateFolder409
    | CreateFolder500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createFolder>>,
    TError,
    { data: CreateFolderBody },
    TContext
  >
  request?: SecondParameter<typeof fetchWithAuth>
}): UseMutationOptions<
  Awaited<ReturnType<typeof createFolder>>,
  TError,
  { data: CreateFolderBody },
  TContext
> => {
  const mutationKey = ['createFolder']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createFolder>>,
    { data: CreateFolderBody }
  > = (props) => {
    const { data } = props ?? {}

    return createFolder(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CreateFolderMutationResult = NonNullable<
  Awaited<ReturnType<typeof createFolder>>
>
export type CreateFolderMutationBody = CreateFolderBody
export type CreateFolderMutationError =
  | CreateFolder400
  | CreateFolder401
  | CreateFolder409
  | CreateFolder500

/**
 * @summary Create Folder
 */
export const useCreateFolder = <
  TError =
    | CreateFolder400
    | CreateFolder401
    | CreateFolder409
    | CreateFolder500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createFolder>>,
      TError,
      { data: CreateFolderBody },
      TContext
    >
    request?: SecondParameter<typeof fetchWithAuth>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createFolder>>,
  TError,
  { data: CreateFolderBody },
  TContext
> => {
  return useMutation(getCreateFolderMutationOptions(options), queryClient)
}
/**
 * List folders. Optionally filter by parentId.
 * @summary Get Folders
 */
export type getFoldersResponse200 = {
  data: GetFolders200
  status: 200
}

export type getFoldersResponse401 = {
  data: GetFolders401
  status: 401
}

export type getFoldersResponse500 = {
  data: GetFolders500
  status: 500
}

export type getFoldersResponseSuccess = getFoldersResponse200 & {
  headers: Headers
}
export type getFoldersResponseError = (
  | getFoldersResponse401
  | getFoldersResponse500
) & {
  headers: Headers
}

export type getFoldersResponse =
  | getFoldersResponseSuccess
  | getFoldersResponseError

export const getGetFoldersUrl = (params?: GetFoldersParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `http://localhost:3333/api/folders?${stringifiedParams}`
    : `http://localhost:3333/api/folders`
}

export const getFolders = async (
  params?: GetFoldersParams,
  options?: RequestInit,
): Promise<getFoldersResponse> => {
  return fetchWithAuth<getFoldersResponse>(getGetFoldersUrl(params), {
    ...options,
    method: 'GET',
  })
}

export const getGetFoldersQueryKey = (params?: GetFoldersParams) => {
  return QUERY_KEYS.folders(params)
}

export const getGetFoldersQueryOptions = <
  TData = Awaited<ReturnType<typeof getFolders>>,
  TError = GetFolders401 | GetFolders500,
>(
  params?: GetFoldersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFolders>>, TError, TData>
    >
    request?: SecondParameter<typeof fetchWithAuth>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetFoldersQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getFolders>>> = ({
    signal,
  }) => getFolders(params, { signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getFolders>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFoldersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFolders>>
>
export type GetFoldersQueryError = GetFolders401 | GetFolders500

export function useGetFolders<
  TData = Awaited<ReturnType<typeof getFolders>>,
  TError = GetFolders401 | GetFolders500,
>(
  params: undefined | GetFoldersParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFolders>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFolders>>,
          TError,
          Awaited<ReturnType<typeof getFolders>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof fetchWithAuth>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetFolders<
  TData = Awaited<ReturnType<typeof getFolders>>,
  TError = GetFolders401 | GetFolders500,
>(
  params?: GetFoldersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFolders>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFolders>>,
          TError,
          Awaited<ReturnType<typeof getFolders>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof fetchWithAuth>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetFolders<
  TData = Awaited<ReturnType<typeof getFolders>>,
  TError = GetFolders401 | GetFolders500,
>(
  params?: GetFoldersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFolders>>, TError, TData>
    >
    request?: SecondParameter<typeof fetchWithAuth>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get Folders
 */

export function useGetFolders<
  TData = Awaited<ReturnType<typeof getFolders>>,
  TError = GetFolders401 | GetFolders500,
>(
  params?: GetFoldersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFolders>>, TError, TData>
    >
    request?: SecondParameter<typeof fetchWithAuth>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetFoldersQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export const getGetFoldersSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getFolders>>,
  TError = GetFolders401 | GetFolders500,
>(
  params?: GetFoldersParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getFolders>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof fetchWithAuth>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetFoldersQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getFolders>>> = ({
    signal,
  }) => getFolders(params, { signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getFolders>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFoldersSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFolders>>
>
export type GetFoldersSuspenseQueryError = GetFolders401 | GetFolders500

export function useGetFoldersSuspense<
  TData = Awaited<ReturnType<typeof getFolders>>,
  TError = GetFolders401 | GetFolders500,
>(
  params: undefined | GetFoldersParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getFolders>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof fetchWithAuth>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetFoldersSuspense<
  TData = Awaited<ReturnType<typeof getFolders>>,
  TError = GetFolders401 | GetFolders500,
>(
  params?: GetFoldersParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getFolders>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof fetchWithAuth>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetFoldersSuspense<
  TData = Awaited<ReturnType<typeof getFolders>>,
  TError = GetFolders401 | GetFolders500,
>(
  params?: GetFoldersParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getFolders>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof fetchWithAuth>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get Folders
 */

export function useGetFoldersSuspense<
  TData = Awaited<ReturnType<typeof getFolders>>,
  TError = GetFolders401 | GetFolders500,
>(
  params?: GetFoldersParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getFolders>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof fetchWithAuth>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetFoldersSuspenseQueryOptions(params, options)

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * Assign an existing tag to a folder
 * @summary Assign Tag to Folder
 */
export type assignTagToFolderResponse204 = {
  data: unknown
  status: 204
}

export type assignTagToFolderResponse401 = {
  data: AssignTagToFolder401
  status: 401
}

export type assignTagToFolderResponse404 = {
  data: AssignTagToFolder404
  status: 404
}

export type assignTagToFolderResponse500 = {
  data: AssignTagToFolder500
  status: 500
}

export type assignTagToFolderResponseSuccess = assignTagToFolderResponse204 & {
  headers: Headers
}
export type assignTagToFolderResponseError = (
  | assignTagToFolderResponse401
  | assignTagToFolderResponse404
  | assignTagToFolderResponse500
) & {
  headers: Headers
}

export type assignTagToFolderResponse =
  | assignTagToFolderResponseSuccess
  | assignTagToFolderResponseError

export const getAssignTagToFolderUrl = (folderId: string, tagId: string) => {
  return `http://localhost:3333/api/folders/${folderId}/tags/${tagId}`
}

export const assignTagToFolder = async (
  folderId: string,
  tagId: string,
  options?: RequestInit,
): Promise<assignTagToFolderResponse> => {
  return fetchWithAuth<assignTagToFolderResponse>(
    getAssignTagToFolderUrl(folderId, tagId),
    {
      ...options,
      method: 'PATCH',
    },
  )
}

export const getAssignTagToFolderMutationOptions = <
  TError = AssignTagToFolder401 | AssignTagToFolder404 | AssignTagToFolder500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof assignTagToFolder>>,
    TError,
    { folderId: string; tagId: string },
    TContext
  >
  request?: SecondParameter<typeof fetchWithAuth>
}): UseMutationOptions<
  Awaited<ReturnType<typeof assignTagToFolder>>,
  TError,
  { folderId: string; tagId: string },
  TContext
> => {
  const mutationKey = ['assignTagToFolder']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof assignTagToFolder>>,
    { folderId: string; tagId: string }
  > = (props) => {
    const { folderId, tagId } = props ?? {}

    return assignTagToFolder(folderId, tagId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AssignTagToFolderMutationResult = NonNullable<
  Awaited<ReturnType<typeof assignTagToFolder>>
>

export type AssignTagToFolderMutationError =
  | AssignTagToFolder401
  | AssignTagToFolder404
  | AssignTagToFolder500

/**
 * @summary Assign Tag to Folder
 */
export const useAssignTagToFolder = <
  TError = AssignTagToFolder401 | AssignTagToFolder404 | AssignTagToFolder500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof assignTagToFolder>>,
      TError,
      { folderId: string; tagId: string },
      TContext
    >
    request?: SecondParameter<typeof fetchWithAuth>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof assignTagToFolder>>,
  TError,
  { folderId: string; tagId: string },
  TContext
> => {
  return useMutation(getAssignTagToFolderMutationOptions(options), queryClient)
}
