/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Rootly API
 * OpenAPI spec version: 0.1.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'
import { useMutation, useQuery } from '@tanstack/react-query'

import type {
  AssignTagToFolder404,
  AssignTagToFolder500,
  CreateFolder201,
  CreateFolder400,
  CreateFolder409,
  CreateFolder500,
  CreateFolderBody,
  GetFolders200,
  GetFolders500,
  GetFoldersParams,
} from '../model'

/**
 * Create a new folder
 * @summary Create Folder
 */
export type createFolderResponse201 = {
  data: CreateFolder201
  status: 201
}

export type createFolderResponse400 = {
  data: CreateFolder400
  status: 400
}

export type createFolderResponse409 = {
  data: CreateFolder409
  status: 409
}

export type createFolderResponse500 = {
  data: CreateFolder500
  status: 500
}

export type createFolderResponseSuccess = createFolderResponse201 & {
  headers: Headers
}
export type createFolderResponseError = (
  | createFolderResponse400
  | createFolderResponse409
  | createFolderResponse500
) & {
  headers: Headers
}

export type createFolderResponse =
  | createFolderResponseSuccess
  | createFolderResponseError

export const getCreateFolderUrl = () => {
  return `http://localhost:3000/api/folders`
}

export const createFolder = async (
  createFolderBody: CreateFolderBody,
  options?: RequestInit,
): Promise<createFolderResponse> => {
  const res = await fetch(getCreateFolderUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createFolderBody),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: createFolderResponse['data'] = body ? JSON.parse(body) : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as createFolderResponse
}

export const getCreateFolderMutationOptions = <
  TError = CreateFolder400 | CreateFolder409 | CreateFolder500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createFolder>>,
    TError,
    { data: CreateFolderBody },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof createFolder>>,
  TError,
  { data: CreateFolderBody },
  TContext
> => {
  const mutationKey = ['createFolder']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createFolder>>,
    { data: CreateFolderBody }
  > = (props) => {
    const { data } = props ?? {}

    return createFolder(data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CreateFolderMutationResult = NonNullable<
  Awaited<ReturnType<typeof createFolder>>
>
export type CreateFolderMutationBody = CreateFolderBody
export type CreateFolderMutationError =
  | CreateFolder400
  | CreateFolder409
  | CreateFolder500

/**
 * @summary Create Folder
 */
export const useCreateFolder = <
  TError = CreateFolder400 | CreateFolder409 | CreateFolder500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createFolder>>,
      TError,
      { data: CreateFolderBody },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createFolder>>,
  TError,
  { data: CreateFolderBody },
  TContext
> => {
  return useMutation(getCreateFolderMutationOptions(options), queryClient)
}
/**
 * List folders. Optionally filter by parentId.
 * @summary Get Folders
 */
export type getFoldersResponse200 = {
  data: GetFolders200
  status: 200
}

export type getFoldersResponse500 = {
  data: GetFolders500
  status: 500
}

export type getFoldersResponseSuccess = getFoldersResponse200 & {
  headers: Headers
}
export type getFoldersResponseError = getFoldersResponse500 & {
  headers: Headers
}

export type getFoldersResponse =
  | getFoldersResponseSuccess
  | getFoldersResponseError

export const getGetFoldersUrl = (params?: GetFoldersParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `http://localhost:3000/api/folders?${stringifiedParams}`
    : `http://localhost:3000/api/folders`
}

export const getFolders = async (
  params?: GetFoldersParams,
  options?: RequestInit,
): Promise<getFoldersResponse> => {
  const res = await fetch(getGetFoldersUrl(params), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: getFoldersResponse['data'] = body ? JSON.parse(body) : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getFoldersResponse
}

export const getGetFoldersQueryKey = (params?: GetFoldersParams) => {
  return [
    `http://localhost:3000/api/folders`,
    ...(params ? [params] : []),
  ] as const
}

export const getGetFoldersQueryOptions = <
  TData = Awaited<ReturnType<typeof getFolders>>,
  TError = GetFolders500,
>(
  params?: GetFoldersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFolders>>, TError, TData>
    >
    fetch?: RequestInit
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetFoldersQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getFolders>>> = ({
    signal,
  }) => getFolders(params, { signal, ...fetchOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getFolders>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFoldersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFolders>>
>
export type GetFoldersQueryError = GetFolders500

export function useGetFolders<
  TData = Awaited<ReturnType<typeof getFolders>>,
  TError = GetFolders500,
>(
  params: undefined | GetFoldersParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFolders>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFolders>>,
          TError,
          Awaited<ReturnType<typeof getFolders>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetFolders<
  TData = Awaited<ReturnType<typeof getFolders>>,
  TError = GetFolders500,
>(
  params?: GetFoldersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFolders>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFolders>>,
          TError,
          Awaited<ReturnType<typeof getFolders>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetFolders<
  TData = Awaited<ReturnType<typeof getFolders>>,
  TError = GetFolders500,
>(
  params?: GetFoldersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFolders>>, TError, TData>
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get Folders
 */

export function useGetFolders<
  TData = Awaited<ReturnType<typeof getFolders>>,
  TError = GetFolders500,
>(
  params?: GetFoldersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFolders>>, TError, TData>
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetFoldersQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * Assign an existing tag to a folder
 * @summary Assign Tag to Folder
 */
export type assignTagToFolderResponse204 = {
  data: unknown
  status: 204
}

export type assignTagToFolderResponse404 = {
  data: AssignTagToFolder404
  status: 404
}

export type assignTagToFolderResponse500 = {
  data: AssignTagToFolder500
  status: 500
}

export type assignTagToFolderResponseSuccess = assignTagToFolderResponse204 & {
  headers: Headers
}
export type assignTagToFolderResponseError = (
  | assignTagToFolderResponse404
  | assignTagToFolderResponse500
) & {
  headers: Headers
}

export type assignTagToFolderResponse =
  | assignTagToFolderResponseSuccess
  | assignTagToFolderResponseError

export const getAssignTagToFolderUrl = (folderId: string, tagId: string) => {
  return `http://localhost:3000/api/folders/${folderId}/tags/${tagId}`
}

export const assignTagToFolder = async (
  folderId: string,
  tagId: string,
  options?: RequestInit,
): Promise<assignTagToFolderResponse> => {
  const res = await fetch(getAssignTagToFolderUrl(folderId, tagId), {
    ...options,
    method: 'PATCH',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: assignTagToFolderResponse['data'] = body ? JSON.parse(body) : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as assignTagToFolderResponse
}

export const getAssignTagToFolderMutationOptions = <
  TError = AssignTagToFolder404 | AssignTagToFolder500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof assignTagToFolder>>,
    TError,
    { folderId: string; tagId: string },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof assignTagToFolder>>,
  TError,
  { folderId: string; tagId: string },
  TContext
> => {
  const mutationKey = ['assignTagToFolder']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof assignTagToFolder>>,
    { folderId: string; tagId: string }
  > = (props) => {
    const { folderId, tagId } = props ?? {}

    return assignTagToFolder(folderId, tagId, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AssignTagToFolderMutationResult = NonNullable<
  Awaited<ReturnType<typeof assignTagToFolder>>
>

export type AssignTagToFolderMutationError =
  | AssignTagToFolder404
  | AssignTagToFolder500

/**
 * @summary Assign Tag to Folder
 */
export const useAssignTagToFolder = <
  TError = AssignTagToFolder404 | AssignTagToFolder500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof assignTagToFolder>>,
      TError,
      { folderId: string; tagId: string },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof assignTagToFolder>>,
  TError,
  { folderId: string; tagId: string },
  TContext
> => {
  return useMutation(getAssignTagToFolderMutationOptions(options), queryClient)
}
