packages:
  - packages/**
  - apps/**

allowBuilds:
  argon2: true
  cpu-features: true
  esbuild: true
  msw: true
  protobufjs: true
  ssh2: true

catalog:
  '@biomejs/biome': 2.4.10
  '@types/node': ^24.10.1
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': ^5.1.1
  react: ^19.2.0
  react-dom: ^19.2.0
  typescript: ^5.9.3
  vite: ^7.3.1

onlyBuiltDependencies:
  - argon2
  - cpu-features
  - esbuild
  - msw
  - protobufjs
  - sharp
  - ssh2
