/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Rootly API
 * OpenAPI spec version: 0.1.0
 */

import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query'
import { useMutation } from '@tanstack/react-query'
import { fetchWithAuth } from '../../lib/fetch'
import type {
  AcceptInvite200,
  AcceptInvite401,
  AcceptInvite403,
  AcceptInvite404,
  AcceptInvite409,
  AcceptInvite500,
  DeclineInvite401,
  DeclineInvite403,
  DeclineInvite404,
  DeclineInvite409,
  DeclineInvite500,
} from '../model'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Accept a workspace invite
 * @summary Accept Invite
 */
export type acceptInviteResponse200 = {
  data: AcceptInvite200
  status: 200
}

export type acceptInviteResponse401 = {
  data: AcceptInvite401
  status: 401
}

export type acceptInviteResponse403 = {
  data: AcceptInvite403
  status: 403
}

export type acceptInviteResponse404 = {
  data: AcceptInvite404
  status: 404
}

export type acceptInviteResponse409 = {
  data: AcceptInvite409
  status: 409
}

export type acceptInviteResponse500 = {
  data: AcceptInvite500
  status: 500
}

export type acceptInviteResponseSuccess = acceptInviteResponse200 & {
  headers: Headers
}
export type acceptInviteResponseError = (
  | acceptInviteResponse401
  | acceptInviteResponse403
  | acceptInviteResponse404
  | acceptInviteResponse409
  | acceptInviteResponse500
) & {
  headers: Headers
}

export type acceptInviteResponse =
  | acceptInviteResponseSuccess
  | acceptInviteResponseError

export const getAcceptInviteUrl = (inviteId: string) => {
  return `http://localhost:3333/api/invites/${inviteId}/accept`
}

export const acceptInvite = async (
  inviteId: string,
  options?: RequestInit,
): Promise<acceptInviteResponse> => {
  return fetchWithAuth<acceptInviteResponse>(getAcceptInviteUrl(inviteId), {
    ...options,
    method: 'POST',
  })
}

export const getAcceptInviteMutationOptions = <
  TError =
    | AcceptInvite401
    | AcceptInvite403
    | AcceptInvite404
    | AcceptInvite409
    | AcceptInvite500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof acceptInvite>>,
    TError,
    { inviteId: string },
    TContext
  >
  request?: SecondParameter<typeof fetchWithAuth>
}): UseMutationOptions<
  Awaited<ReturnType<typeof acceptInvite>>,
  TError,
  { inviteId: string },
  TContext
> => {
  const mutationKey = ['acceptInvite']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof acceptInvite>>,
    { inviteId: string }
  > = (props) => {
    const { inviteId } = props ?? {}

    return acceptInvite(inviteId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AcceptInviteMutationResult = NonNullable<
  Awaited<ReturnType<typeof acceptInvite>>
>

export type AcceptInviteMutationError =
  | AcceptInvite401
  | AcceptInvite403
  | AcceptInvite404
  | AcceptInvite409
  | AcceptInvite500

/**
 * @summary Accept Invite
 */
export const useAcceptInvite = <
  TError =
    | AcceptInvite401
    | AcceptInvite403
    | AcceptInvite404
    | AcceptInvite409
    | AcceptInvite500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof acceptInvite>>,
      TError,
      { inviteId: string },
      TContext
    >
    request?: SecondParameter<typeof fetchWithAuth>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof acceptInvite>>,
  TError,
  { inviteId: string },
  TContext
> => {
  return useMutation(getAcceptInviteMutationOptions(options), queryClient)
}
/**
 * Decline a workspace invite
 * @summary Decline Invite
 */
export type declineInviteResponse204 = {
  data: void
  status: 204
}

export type declineInviteResponse401 = {
  data: DeclineInvite401
  status: 401
}

export type declineInviteResponse403 = {
  data: DeclineInvite403
  status: 403
}

export type declineInviteResponse404 = {
  data: DeclineInvite404
  status: 404
}

export type declineInviteResponse409 = {
  data: DeclineInvite409
  status: 409
}

export type declineInviteResponse500 = {
  data: DeclineInvite500
  status: 500
}

export type declineInviteResponseSuccess = declineInviteResponse204 & {
  headers: Headers
}
export type declineInviteResponseError = (
  | declineInviteResponse401
  | declineInviteResponse403
  | declineInviteResponse404
  | declineInviteResponse409
  | declineInviteResponse500
) & {
  headers: Headers
}

export type declineInviteResponse =
  | declineInviteResponseSuccess
  | declineInviteResponseError

export const getDeclineInviteUrl = (inviteId: string) => {
  return `http://localhost:3333/api/invites/${inviteId}/decline`
}

export const declineInvite = async (
  inviteId: string,
  options?: RequestInit,
): Promise<declineInviteResponse> => {
  return fetchWithAuth<declineInviteResponse>(getDeclineInviteUrl(inviteId), {
    ...options,
    method: 'POST',
  })
}

export const getDeclineInviteMutationOptions = <
  TError =
    | DeclineInvite401
    | DeclineInvite403
    | DeclineInvite404
    | DeclineInvite409
    | DeclineInvite500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof declineInvite>>,
    TError,
    { inviteId: string },
    TContext
  >
  request?: SecondParameter<typeof fetchWithAuth>
}): UseMutationOptions<
  Awaited<ReturnType<typeof declineInvite>>,
  TError,
  { inviteId: string },
  TContext
> => {
  const mutationKey = ['declineInvite']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof declineInvite>>,
    { inviteId: string }
  > = (props) => {
    const { inviteId } = props ?? {}

    return declineInvite(inviteId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeclineInviteMutationResult = NonNullable<
  Awaited<ReturnType<typeof declineInvite>>
>

export type DeclineInviteMutationError =
  | DeclineInvite401
  | DeclineInvite403
  | DeclineInvite404
  | DeclineInvite409
  | DeclineInvite500

/**
 * @summary Decline Invite
 */
export const useDeclineInvite = <
  TError =
    | DeclineInvite401
    | DeclineInvite403
    | DeclineInvite404
    | DeclineInvite409
    | DeclineInvite500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof declineInvite>>,
      TError,
      { inviteId: string },
      TContext
    >
    request?: SecondParameter<typeof fetchWithAuth>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof declineInvite>>,
  TError,
  { inviteId: string },
  TContext
> => {
  return useMutation(getDeclineInviteMutationOptions(options), queryClient)
}
