/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as SignupRouteImport } from './pages/signup'
import { Route as SessionRouteImport } from './pages/session'
import { Route as AuthenticatedLayoutRouteImport } from './pages/_authenticated/layout'
import { Route as AuthenticateddashboardIndexRouteImport } from './pages/_authenticated/(dashboard)/index'
import { Route as AuthenticatedWorkspaceIdIndexRouteImport } from './pages/_authenticated/$workspaceId/index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLayoutRoute = AuthenticatedLayoutRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticateddashboardIndexRoute =
  AuthenticateddashboardIndexRouteImport.update({
    id: '/(dashboard)/',
    path: '/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedWorkspaceIdIndexRoute =
  AuthenticatedWorkspaceIdIndexRouteImport.update({
    id: '/$workspaceId/',
    path: '/$workspaceId/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticateddashboardIndexRoute
  '/session': typeof SessionRoute
  '/signup': typeof SignupRoute
  '/$workspaceId/': typeof AuthenticatedWorkspaceIdIndexRoute
}
export interface FileRoutesByTo {
  '/session': typeof SessionRoute
  '/signup': typeof SignupRoute
  '/$workspaceId': typeof AuthenticatedWorkspaceIdIndexRoute
  '/': typeof AuthenticateddashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedLayoutRouteWithChildren
  '/session': typeof SessionRoute
  '/signup': typeof SignupRoute
  '/_authenticated/$workspaceId/': typeof AuthenticatedWorkspaceIdIndexRoute
  '/_authenticated/(dashboard)/': typeof AuthenticateddashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/session' | '/signup' | '/$workspaceId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/session' | '/signup' | '/$workspaceId' | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/session'
    | '/signup'
    | '/_authenticated/$workspaceId/'
    | '/_authenticated/(dashboard)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedLayoutRoute: typeof AuthenticatedLayoutRouteWithChildren
  SessionRoute: typeof SessionRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/(dashboard)/': {
      id: '/_authenticated/(dashboard)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticateddashboardIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/$workspaceId/': {
      id: '/_authenticated/$workspaceId/'
      path: '/$workspaceId'
      fullPath: '/$workspaceId/'
      preLoaderRoute: typeof AuthenticatedWorkspaceIdIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
  }
}

interface AuthenticatedLayoutRouteChildren {
  AuthenticatedWorkspaceIdIndexRoute: typeof AuthenticatedWorkspaceIdIndexRoute
  AuthenticateddashboardIndexRoute: typeof AuthenticateddashboardIndexRoute
}

const AuthenticatedLayoutRouteChildren: AuthenticatedLayoutRouteChildren = {
  AuthenticatedWorkspaceIdIndexRoute: AuthenticatedWorkspaceIdIndexRoute,
  AuthenticateddashboardIndexRoute: AuthenticateddashboardIndexRoute,
}

const AuthenticatedLayoutRouteWithChildren =
  AuthenticatedLayoutRoute._addFileChildren(AuthenticatedLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedLayoutRoute: AuthenticatedLayoutRouteWithChildren,
  SessionRoute: SessionRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
