/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as SignupRouteImport } from './pages/signup'
import { Route as SessionRouteImport } from './pages/session'
import { Route as AuthenticateddashboardIndexRouteImport } from './pages/_authenticated/(dashboard)/index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticateddashboardIndexRoute =
  AuthenticateddashboardIndexRouteImport.update({
    id: '/_authenticated/(dashboard)/',
    path: '/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/session': typeof SessionRoute
  '/signup': typeof SignupRoute
  '/': typeof AuthenticateddashboardIndexRoute
}
export interface FileRoutesByTo {
  '/session': typeof SessionRoute
  '/signup': typeof SignupRoute
  '/': typeof AuthenticateddashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/session': typeof SessionRoute
  '/signup': typeof SignupRoute
  '/_authenticated/(dashboard)/': typeof AuthenticateddashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/session' | '/signup' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/session' | '/signup' | '/'
  id: '__root__' | '/session' | '/signup' | '/_authenticated/(dashboard)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SessionRoute: typeof SessionRoute
  SignupRoute: typeof SignupRoute
  AuthenticateddashboardIndexRoute: typeof AuthenticateddashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/(dashboard)/': {
      id: '/_authenticated/(dashboard)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticateddashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  SessionRoute: SessionRoute,
  SignupRoute: SignupRoute,
  AuthenticateddashboardIndexRoute: AuthenticateddashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
