/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Rootly API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  ArchiveItem401,
  ArchiveItem404,
  ArchiveItem409,
  ArchiveItem500,
  CreateItem201,
  CreateItem400,
  CreateItem401,
  CreateItem409,
  CreateItem500,
  CreateItemBody,
  DeleteItem401,
  DeleteItem404,
  DeleteItem409,
  DeleteItem500,
  GetItems200,
  GetItems401,
  GetItems500,
  GetItemsParams,
  RestoreItem401,
  RestoreItem404,
  RestoreItem409,
  RestoreItem500,
  UploadItem201,
  UploadItem400,
  UploadItem401,
  UploadItem409,
  UploadItem500,
  UploadItemBody
} from '../model';

import { fetchWithAuth } from '../../lib/fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Create a new item
 * @summary Create Item
 */
export type createItemResponse201 = {
  data: CreateItem201
  status: 201
}

export type createItemResponse400 = {
  data: CreateItem400
  status: 400
}

export type createItemResponse401 = {
  data: CreateItem401
  status: 401
}

export type createItemResponse409 = {
  data: CreateItem409
  status: 409
}

export type createItemResponse500 = {
  data: CreateItem500
  status: 500
}

export type createItemResponseSuccess = (createItemResponse201) & {
  headers: Headers;
};
export type createItemResponseError = (createItemResponse400 | createItemResponse401 | createItemResponse409 | createItemResponse500) & {
  headers: Headers;
};

export type createItemResponse = (createItemResponseSuccess | createItemResponseError)

export const getCreateItemUrl = () => {


  

  return `http://localhost:3333/api/items`
}

export const createItem = async (createItemBody: CreateItemBody, options?: RequestInit): Promise<createItemResponse> => {
  
  return fetchWithAuth<createItemResponse>(getCreateItemUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createItemBody,)
  }
);}
  



export const getCreateItemMutationOptions = <TError = CreateItem400 | CreateItem401 | CreateItem409 | CreateItem500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createItem>>, TError,{data: CreateItemBody}, TContext>, request?: SecondParameter<typeof fetchWithAuth>}
): UseMutationOptions<Awaited<ReturnType<typeof createItem>>, TError,{data: CreateItemBody}, TContext> => {

const mutationKey = ['createItem'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createItem>>, {data: CreateItemBody}> = (props) => {
          const {data} = props ?? {};

          return  createItem(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateItemMutationResult = NonNullable<Awaited<ReturnType<typeof createItem>>>
    export type CreateItemMutationBody = CreateItemBody
    export type CreateItemMutationError = CreateItem400 | CreateItem401 | CreateItem409 | CreateItem500

    /**
 * @summary Create Item
 */
export const useCreateItem = <TError = CreateItem400 | CreateItem401 | CreateItem409 | CreateItem500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createItem>>, TError,{data: CreateItemBody}, TContext>, request?: SecondParameter<typeof fetchWithAuth>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createItem>>,
        TError,
        {data: CreateItemBody},
        TContext
      > => {
      return useMutation(getCreateItemMutationOptions(options), queryClient);
    }
    /**
 * List items. Optionally filter by parentId or workspaceId.
 * @summary Get Items
 */
export type getItemsResponse200 = {
  data: GetItems200
  status: 200
}

export type getItemsResponse401 = {
  data: GetItems401
  status: 401
}

export type getItemsResponse500 = {
  data: GetItems500
  status: 500
}

export type getItemsResponseSuccess = (getItemsResponse200) & {
  headers: Headers;
};
export type getItemsResponseError = (getItemsResponse401 | getItemsResponse500) & {
  headers: Headers;
};

export type getItemsResponse = (getItemsResponseSuccess | getItemsResponseError)

export const getGetItemsUrl = (params?: GetItemsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3333/api/items?${stringifiedParams}` : `http://localhost:3333/api/items`
}

export const getItems = async (params?: GetItemsParams, options?: RequestInit): Promise<getItemsResponse> => {
  
  return fetchWithAuth<getItemsResponse>(getGetItemsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getGetItemsQueryKey = (params?: GetItemsParams,) => {
    return [
    'http:','localhost:3333','api','items', ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetItemsQueryOptions = <TData = Awaited<ReturnType<typeof getItems>>, TError = GetItems401 | GetItems500>(params?: GetItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItems>>, TError, TData>>, request?: SecondParameter<typeof fetchWithAuth>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetItemsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getItems>>> = ({ signal }) => getItems(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getItems>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetItemsQueryResult = NonNullable<Awaited<ReturnType<typeof getItems>>>
export type GetItemsQueryError = GetItems401 | GetItems500


export function useGetItems<TData = Awaited<ReturnType<typeof getItems>>, TError = GetItems401 | GetItems500>(
 params: undefined |  GetItemsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItems>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getItems>>,
          TError,
          Awaited<ReturnType<typeof getItems>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetchWithAuth>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetItems<TData = Awaited<ReturnType<typeof getItems>>, TError = GetItems401 | GetItems500>(
 params?: GetItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItems>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getItems>>,
          TError,
          Awaited<ReturnType<typeof getItems>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetchWithAuth>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetItems<TData = Awaited<ReturnType<typeof getItems>>, TError = GetItems401 | GetItems500>(
 params?: GetItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItems>>, TError, TData>>, request?: SecondParameter<typeof fetchWithAuth>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Items
 */

export function useGetItems<TData = Awaited<ReturnType<typeof getItems>>, TError = GetItems401 | GetItems500>(
 params?: GetItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItems>>, TError, TData>>, request?: SecondParameter<typeof fetchWithAuth>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetItemsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetItemsSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getItems>>, TError = GetItems401 | GetItems500>(params?: GetItemsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getItems>>, TError, TData>>, request?: SecondParameter<typeof fetchWithAuth>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetItemsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getItems>>> = ({ signal }) => getItems(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getItems>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetItemsSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getItems>>>
export type GetItemsSuspenseQueryError = GetItems401 | GetItems500


export function useGetItemsSuspense<TData = Awaited<ReturnType<typeof getItems>>, TError = GetItems401 | GetItems500>(
 params: undefined |  GetItemsParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getItems>>, TError, TData>>, request?: SecondParameter<typeof fetchWithAuth>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetItemsSuspense<TData = Awaited<ReturnType<typeof getItems>>, TError = GetItems401 | GetItems500>(
 params?: GetItemsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getItems>>, TError, TData>>, request?: SecondParameter<typeof fetchWithAuth>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetItemsSuspense<TData = Awaited<ReturnType<typeof getItems>>, TError = GetItems401 | GetItems500>(
 params?: GetItemsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getItems>>, TError, TData>>, request?: SecondParameter<typeof fetchWithAuth>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Items
 */

export function useGetItemsSuspense<TData = Awaited<ReturnType<typeof getItems>>, TError = GetItems401 | GetItems500>(
 params?: GetItemsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getItems>>, TError, TData>>, request?: SecondParameter<typeof fetchWithAuth>}
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetItemsSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Create a document item by uploading a file via multipart/form-data
 * @summary Upload Item
 */
export type uploadItemResponse201 = {
  data: UploadItem201
  status: 201
}

export type uploadItemResponse400 = {
  data: UploadItem400
  status: 400
}

export type uploadItemResponse401 = {
  data: UploadItem401
  status: 401
}

export type uploadItemResponse409 = {
  data: UploadItem409
  status: 409
}

export type uploadItemResponse500 = {
  data: UploadItem500
  status: 500
}

export type uploadItemResponseSuccess = (uploadItemResponse201) & {
  headers: Headers;
};
export type uploadItemResponseError = (uploadItemResponse400 | uploadItemResponse401 | uploadItemResponse409 | uploadItemResponse500) & {
  headers: Headers;
};

export type uploadItemResponse = (uploadItemResponseSuccess | uploadItemResponseError)

export const getUploadItemUrl = () => {


  

  return `http://localhost:3333/api/items/upload`
}

export const uploadItem = async (uploadItemBody: UploadItemBody, options?: RequestInit): Promise<uploadItemResponse> => {
    const formData = new FormData();
formData.append(`title`, uploadItemBody.title);
formData.append(`workspaceId`, uploadItemBody.workspaceId);
if(uploadItemBody.folderId !== undefined) {
 formData.append(`folderId`, uploadItemBody.folderId);
 }
formData.append(`file`, uploadItemBody.file);

  return fetchWithAuth<uploadItemResponse>(getUploadItemUrl(),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
);}
  



export const getUploadItemMutationOptions = <TError = UploadItem400 | UploadItem401 | UploadItem409 | UploadItem500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadItem>>, TError,{data: UploadItemBody}, TContext>, request?: SecondParameter<typeof fetchWithAuth>}
): UseMutationOptions<Awaited<ReturnType<typeof uploadItem>>, TError,{data: UploadItemBody}, TContext> => {

const mutationKey = ['uploadItem'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadItem>>, {data: UploadItemBody}> = (props) => {
          const {data} = props ?? {};

          return  uploadItem(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UploadItemMutationResult = NonNullable<Awaited<ReturnType<typeof uploadItem>>>
    export type UploadItemMutationBody = UploadItemBody
    export type UploadItemMutationError = UploadItem400 | UploadItem401 | UploadItem409 | UploadItem500

    /**
 * @summary Upload Item
 */
export const useUploadItem = <TError = UploadItem400 | UploadItem401 | UploadItem409 | UploadItem500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadItem>>, TError,{data: UploadItemBody}, TContext>, request?: SecondParameter<typeof fetchWithAuth>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uploadItem>>,
        TError,
        {data: UploadItemBody},
        TContext
      > => {
      return useMutation(getUploadItemMutationOptions(options), queryClient);
    }
    /**
 * Archive an item, hiding it from the default view
 * @summary Archive Item
 */
export type archiveItemResponse204 = {
  data: void
  status: 204
}

export type archiveItemResponse401 = {
  data: ArchiveItem401
  status: 401
}

export type archiveItemResponse404 = {
  data: ArchiveItem404
  status: 404
}

export type archiveItemResponse409 = {
  data: ArchiveItem409
  status: 409
}

export type archiveItemResponse500 = {
  data: ArchiveItem500
  status: 500
}

export type archiveItemResponseSuccess = (archiveItemResponse204) & {
  headers: Headers;
};
export type archiveItemResponseError = (archiveItemResponse401 | archiveItemResponse404 | archiveItemResponse409 | archiveItemResponse500) & {
  headers: Headers;
};

export type archiveItemResponse = (archiveItemResponseSuccess | archiveItemResponseError)

export const getArchiveItemUrl = (itemId: string,) => {


  

  return `http://localhost:3333/api/items/${itemId}/archive`
}

export const archiveItem = async (itemId: string, options?: RequestInit): Promise<archiveItemResponse> => {
  
  return fetchWithAuth<archiveItemResponse>(getArchiveItemUrl(itemId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}
  



export const getArchiveItemMutationOptions = <TError = ArchiveItem401 | ArchiveItem404 | ArchiveItem409 | ArchiveItem500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof archiveItem>>, TError,{itemId: string}, TContext>, request?: SecondParameter<typeof fetchWithAuth>}
): UseMutationOptions<Awaited<ReturnType<typeof archiveItem>>, TError,{itemId: string}, TContext> => {

const mutationKey = ['archiveItem'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof archiveItem>>, {itemId: string}> = (props) => {
          const {itemId} = props ?? {};

          return  archiveItem(itemId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ArchiveItemMutationResult = NonNullable<Awaited<ReturnType<typeof archiveItem>>>
    
    export type ArchiveItemMutationError = ArchiveItem401 | ArchiveItem404 | ArchiveItem409 | ArchiveItem500

    /**
 * @summary Archive Item
 */
export const useArchiveItem = <TError = ArchiveItem401 | ArchiveItem404 | ArchiveItem409 | ArchiveItem500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof archiveItem>>, TError,{itemId: string}, TContext>, request?: SecondParameter<typeof fetchWithAuth>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof archiveItem>>,
        TError,
        {itemId: string},
        TContext
      > => {
      return useMutation(getArchiveItemMutationOptions(options), queryClient);
    }
    /**
 * Restore a previously archived item
 * @summary Restore Item
 */
export type restoreItemResponse204 = {
  data: void
  status: 204
}

export type restoreItemResponse401 = {
  data: RestoreItem401
  status: 401
}

export type restoreItemResponse404 = {
  data: RestoreItem404
  status: 404
}

export type restoreItemResponse409 = {
  data: RestoreItem409
  status: 409
}

export type restoreItemResponse500 = {
  data: RestoreItem500
  status: 500
}

export type restoreItemResponseSuccess = (restoreItemResponse204) & {
  headers: Headers;
};
export type restoreItemResponseError = (restoreItemResponse401 | restoreItemResponse404 | restoreItemResponse409 | restoreItemResponse500) & {
  headers: Headers;
};

export type restoreItemResponse = (restoreItemResponseSuccess | restoreItemResponseError)

export const getRestoreItemUrl = (itemId: string,) => {


  

  return `http://localhost:3333/api/items/${itemId}/restore`
}

export const restoreItem = async (itemId: string, options?: RequestInit): Promise<restoreItemResponse> => {
  
  return fetchWithAuth<restoreItemResponse>(getRestoreItemUrl(itemId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}
  



export const getRestoreItemMutationOptions = <TError = RestoreItem401 | RestoreItem404 | RestoreItem409 | RestoreItem500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof restoreItem>>, TError,{itemId: string}, TContext>, request?: SecondParameter<typeof fetchWithAuth>}
): UseMutationOptions<Awaited<ReturnType<typeof restoreItem>>, TError,{itemId: string}, TContext> => {

const mutationKey = ['restoreItem'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof restoreItem>>, {itemId: string}> = (props) => {
          const {itemId} = props ?? {};

          return  restoreItem(itemId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RestoreItemMutationResult = NonNullable<Awaited<ReturnType<typeof restoreItem>>>
    
    export type RestoreItemMutationError = RestoreItem401 | RestoreItem404 | RestoreItem409 | RestoreItem500

    /**
 * @summary Restore Item
 */
export const useRestoreItem = <TError = RestoreItem401 | RestoreItem404 | RestoreItem409 | RestoreItem500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof restoreItem>>, TError,{itemId: string}, TContext>, request?: SecondParameter<typeof fetchWithAuth>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof restoreItem>>,
        TError,
        {itemId: string},
        TContext
      > => {
      return useMutation(getRestoreItemMutationOptions(options), queryClient);
    }
    /**
 * Permanently delete an archived item
 * @summary Delete Item
 */
export type deleteItemResponse204 = {
  data: void
  status: 204
}

export type deleteItemResponse401 = {
  data: DeleteItem401
  status: 401
}

export type deleteItemResponse404 = {
  data: DeleteItem404
  status: 404
}

export type deleteItemResponse409 = {
  data: DeleteItem409
  status: 409
}

export type deleteItemResponse500 = {
  data: DeleteItem500
  status: 500
}

export type deleteItemResponseSuccess = (deleteItemResponse204) & {
  headers: Headers;
};
export type deleteItemResponseError = (deleteItemResponse401 | deleteItemResponse404 | deleteItemResponse409 | deleteItemResponse500) & {
  headers: Headers;
};

export type deleteItemResponse = (deleteItemResponseSuccess | deleteItemResponseError)

export const getDeleteItemUrl = (itemId: string,) => {


  

  return `http://localhost:3333/api/items/${itemId}`
}

export const deleteItem = async (itemId: string, options?: RequestInit): Promise<deleteItemResponse> => {
  
  return fetchWithAuth<deleteItemResponse>(getDeleteItemUrl(itemId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  



export const getDeleteItemMutationOptions = <TError = DeleteItem401 | DeleteItem404 | DeleteItem409 | DeleteItem500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteItem>>, TError,{itemId: string}, TContext>, request?: SecondParameter<typeof fetchWithAuth>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteItem>>, TError,{itemId: string}, TContext> => {

const mutationKey = ['deleteItem'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteItem>>, {itemId: string}> = (props) => {
          const {itemId} = props ?? {};

          return  deleteItem(itemId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteItemMutationResult = NonNullable<Awaited<ReturnType<typeof deleteItem>>>
    
    export type DeleteItemMutationError = DeleteItem401 | DeleteItem404 | DeleteItem409 | DeleteItem500

    /**
 * @summary Delete Item
 */
export const useDeleteItem = <TError = DeleteItem401 | DeleteItem404 | DeleteItem409 | DeleteItem500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteItem>>, TError,{itemId: string}, TContext>, request?: SecondParameter<typeof fetchWithAuth>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteItem>>,
        TError,
        {itemId: string},
        TContext
      > => {
      return useMutation(getDeleteItemMutationOptions(options), queryClient);
    }
    