/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Rootly API
 * OpenAPI spec version: 0.1.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'
import { useMutation, useQuery } from '@tanstack/react-query'

import type {
  AssignTagToItem404,
  AssignTagToItem500,
  CreateItem201,
  CreateItem400,
  CreateItem409,
  CreateItem500,
  CreateItemBody,
  GetItems200,
  GetItems500,
  GetItemsParams,
} from '../model'

/**
 * Create a new item
 * @summary Create Item
 */
export type createItemResponse201 = {
  data: CreateItem201
  status: 201
}

export type createItemResponse400 = {
  data: CreateItem400
  status: 400
}

export type createItemResponse409 = {
  data: CreateItem409
  status: 409
}

export type createItemResponse500 = {
  data: CreateItem500
  status: 500
}

export type createItemResponseSuccess = createItemResponse201 & {
  headers: Headers
}
export type createItemResponseError = (
  | createItemResponse400
  | createItemResponse409
  | createItemResponse500
) & {
  headers: Headers
}

export type createItemResponse =
  | createItemResponseSuccess
  | createItemResponseError

export const getCreateItemUrl = () => {
  return `http://localhost:3000/api/items`
}

export const createItem = async (
  createItemBody: CreateItemBody,
  options?: RequestInit,
): Promise<createItemResponse> => {
  const res = await fetch(getCreateItemUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createItemBody),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: createItemResponse['data'] = body ? JSON.parse(body) : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as createItemResponse
}

export const getCreateItemMutationOptions = <
  TError = CreateItem400 | CreateItem409 | CreateItem500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createItem>>,
    TError,
    { data: CreateItemBody },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof createItem>>,
  TError,
  { data: CreateItemBody },
  TContext
> => {
  const mutationKey = ['createItem']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createItem>>,
    { data: CreateItemBody }
  > = (props) => {
    const { data } = props ?? {}

    return createItem(data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CreateItemMutationResult = NonNullable<
  Awaited<ReturnType<typeof createItem>>
>
export type CreateItemMutationBody = CreateItemBody
export type CreateItemMutationError =
  | CreateItem400
  | CreateItem409
  | CreateItem500

/**
 * @summary Create Item
 */
export const useCreateItem = <
  TError = CreateItem400 | CreateItem409 | CreateItem500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createItem>>,
      TError,
      { data: CreateItemBody },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createItem>>,
  TError,
  { data: CreateItemBody },
  TContext
> => {
  return useMutation(getCreateItemMutationOptions(options), queryClient)
}
/**
 * List items. Optionally filter by parentId.
 * @summary Get Items
 */
export type getItemsResponse200 = {
  data: GetItems200
  status: 200
}

export type getItemsResponse500 = {
  data: GetItems500
  status: 500
}

export type getItemsResponseSuccess = getItemsResponse200 & {
  headers: Headers
}
export type getItemsResponseError = getItemsResponse500 & {
  headers: Headers
}

export type getItemsResponse = getItemsResponseSuccess | getItemsResponseError

export const getGetItemsUrl = (params?: GetItemsParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `http://localhost:3000/api/items?${stringifiedParams}`
    : `http://localhost:3000/api/items`
}

export const getItems = async (
  params?: GetItemsParams,
  options?: RequestInit,
): Promise<getItemsResponse> => {
  const res = await fetch(getGetItemsUrl(params), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: getItemsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getItemsResponse
}

export const getGetItemsQueryKey = (params?: GetItemsParams) => {
  return [
    `http://localhost:3000/api/items`,
    ...(params ? [params] : []),
  ] as const
}

export const getGetItemsQueryOptions = <
  TData = Awaited<ReturnType<typeof getItems>>,
  TError = GetItems500,
>(
  params?: GetItemsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getItems>>, TError, TData>
    >
    fetch?: RequestInit
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetItemsQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getItems>>> = ({
    signal,
  }) => getItems(params, { signal, ...fetchOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getItems>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetItemsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getItems>>
>
export type GetItemsQueryError = GetItems500

export function useGetItems<
  TData = Awaited<ReturnType<typeof getItems>>,
  TError = GetItems500,
>(
  params: undefined | GetItemsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getItems>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getItems>>,
          TError,
          Awaited<ReturnType<typeof getItems>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetItems<
  TData = Awaited<ReturnType<typeof getItems>>,
  TError = GetItems500,
>(
  params?: GetItemsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getItems>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getItems>>,
          TError,
          Awaited<ReturnType<typeof getItems>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetItems<
  TData = Awaited<ReturnType<typeof getItems>>,
  TError = GetItems500,
>(
  params?: GetItemsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getItems>>, TError, TData>
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get Items
 */

export function useGetItems<
  TData = Awaited<ReturnType<typeof getItems>>,
  TError = GetItems500,
>(
  params?: GetItemsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getItems>>, TError, TData>
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetItemsQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * Assign an existing tag to an item
 * @summary Assign Tag to Item
 */
export type assignTagToItemResponse204 = {
  data: unknown
  status: 204
}

export type assignTagToItemResponse404 = {
  data: AssignTagToItem404
  status: 404
}

export type assignTagToItemResponse500 = {
  data: AssignTagToItem500
  status: 500
}

export type assignTagToItemResponseSuccess = assignTagToItemResponse204 & {
  headers: Headers
}
export type assignTagToItemResponseError = (
  | assignTagToItemResponse404
  | assignTagToItemResponse500
) & {
  headers: Headers
}

export type assignTagToItemResponse =
  | assignTagToItemResponseSuccess
  | assignTagToItemResponseError

export const getAssignTagToItemUrl = (itemId: string, tagId: string) => {
  return `http://localhost:3000/api/items/${itemId}/tags/${tagId}`
}

export const assignTagToItem = async (
  itemId: string,
  tagId: string,
  options?: RequestInit,
): Promise<assignTagToItemResponse> => {
  const res = await fetch(getAssignTagToItemUrl(itemId, tagId), {
    ...options,
    method: 'PATCH',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: assignTagToItemResponse['data'] = body ? JSON.parse(body) : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as assignTagToItemResponse
}

export const getAssignTagToItemMutationOptions = <
  TError = AssignTagToItem404 | AssignTagToItem500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof assignTagToItem>>,
    TError,
    { itemId: string; tagId: string },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof assignTagToItem>>,
  TError,
  { itemId: string; tagId: string },
  TContext
> => {
  const mutationKey = ['assignTagToItem']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof assignTagToItem>>,
    { itemId: string; tagId: string }
  > = (props) => {
    const { itemId, tagId } = props ?? {}

    return assignTagToItem(itemId, tagId, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AssignTagToItemMutationResult = NonNullable<
  Awaited<ReturnType<typeof assignTagToItem>>
>

export type AssignTagToItemMutationError =
  | AssignTagToItem404
  | AssignTagToItem500

/**
 * @summary Assign Tag to Item
 */
export const useAssignTagToItem = <
  TError = AssignTagToItem404 | AssignTagToItem500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof assignTagToItem>>,
      TError,
      { itemId: string; tagId: string },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof assignTagToItem>>,
  TError,
  { itemId: string; tagId: string },
  TContext
> => {
  return useMutation(getAssignTagToItemMutationOptions(options), queryClient)
}
