/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Rootly API
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  GetActivityLogs200,
  GetActivityLogs401,
  GetActivityLogs403,
  GetActivityLogs404,
  GetActivityLogs500,
  GetActivityLogsParams
} from '../model';

import { fetchWithAuth } from '../../lib/fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * List the activity log of a workspace, optionally filtered by resourceId or resourceType
 * @summary Get Activity Logs
 */
export type getActivityLogsResponse200 = {
  data: GetActivityLogs200
  status: 200
}

export type getActivityLogsResponse401 = {
  data: GetActivityLogs401
  status: 401
}

export type getActivityLogsResponse403 = {
  data: GetActivityLogs403
  status: 403
}

export type getActivityLogsResponse404 = {
  data: GetActivityLogs404
  status: 404
}

export type getActivityLogsResponse500 = {
  data: GetActivityLogs500
  status: 500
}

export type getActivityLogsResponseSuccess = (getActivityLogsResponse200) & {
  headers: Headers;
};
export type getActivityLogsResponseError = (getActivityLogsResponse401 | getActivityLogsResponse403 | getActivityLogsResponse404 | getActivityLogsResponse500) & {
  headers: Headers;
};

export type getActivityLogsResponse = (getActivityLogsResponseSuccess | getActivityLogsResponseError)

export const getGetActivityLogsUrl = (workspaceId: string,
    params?: GetActivityLogsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3333/api/workspaces/${workspaceId}/activity?${stringifiedParams}` : `http://localhost:3333/api/workspaces/${workspaceId}/activity`
}

export const getActivityLogs = async (workspaceId: string,
    params?: GetActivityLogsParams, options?: RequestInit): Promise<getActivityLogsResponse> => {
  
  return fetchWithAuth<getActivityLogsResponse>(getGetActivityLogsUrl(workspaceId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getGetActivityLogsQueryKey = (workspaceId: string,
    params?: GetActivityLogsParams,) => {
    return [
    'http:','localhost:3333','api','workspaces',workspaceId,'activity', ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetActivityLogsQueryOptions = <TData = Awaited<ReturnType<typeof getActivityLogs>>, TError = GetActivityLogs401 | GetActivityLogs403 | GetActivityLogs404 | GetActivityLogs500>(workspaceId: string,
    params?: GetActivityLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActivityLogs>>, TError, TData>>, request?: SecondParameter<typeof fetchWithAuth>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetActivityLogsQueryKey(workspaceId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getActivityLogs>>> = ({ signal }) => getActivityLogs(workspaceId,params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(workspaceId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getActivityLogs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetActivityLogsQueryResult = NonNullable<Awaited<ReturnType<typeof getActivityLogs>>>
export type GetActivityLogsQueryError = GetActivityLogs401 | GetActivityLogs403 | GetActivityLogs404 | GetActivityLogs500


export function useGetActivityLogs<TData = Awaited<ReturnType<typeof getActivityLogs>>, TError = GetActivityLogs401 | GetActivityLogs403 | GetActivityLogs404 | GetActivityLogs500>(
 workspaceId: string,
    params: undefined |  GetActivityLogsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActivityLogs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getActivityLogs>>,
          TError,
          Awaited<ReturnType<typeof getActivityLogs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetchWithAuth>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetActivityLogs<TData = Awaited<ReturnType<typeof getActivityLogs>>, TError = GetActivityLogs401 | GetActivityLogs403 | GetActivityLogs404 | GetActivityLogs500>(
 workspaceId: string,
    params?: GetActivityLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActivityLogs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getActivityLogs>>,
          TError,
          Awaited<ReturnType<typeof getActivityLogs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetchWithAuth>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetActivityLogs<TData = Awaited<ReturnType<typeof getActivityLogs>>, TError = GetActivityLogs401 | GetActivityLogs403 | GetActivityLogs404 | GetActivityLogs500>(
 workspaceId: string,
    params?: GetActivityLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActivityLogs>>, TError, TData>>, request?: SecondParameter<typeof fetchWithAuth>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Activity Logs
 */

export function useGetActivityLogs<TData = Awaited<ReturnType<typeof getActivityLogs>>, TError = GetActivityLogs401 | GetActivityLogs403 | GetActivityLogs404 | GetActivityLogs500>(
 workspaceId: string,
    params?: GetActivityLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActivityLogs>>, TError, TData>>, request?: SecondParameter<typeof fetchWithAuth>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetActivityLogsQueryOptions(workspaceId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetActivityLogsSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getActivityLogs>>, TError = GetActivityLogs401 | GetActivityLogs403 | GetActivityLogs404 | GetActivityLogs500>(workspaceId: string,
    params?: GetActivityLogsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getActivityLogs>>, TError, TData>>, request?: SecondParameter<typeof fetchWithAuth>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetActivityLogsQueryKey(workspaceId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getActivityLogs>>> = ({ signal }) => getActivityLogs(workspaceId,params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getActivityLogs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetActivityLogsSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getActivityLogs>>>
export type GetActivityLogsSuspenseQueryError = GetActivityLogs401 | GetActivityLogs403 | GetActivityLogs404 | GetActivityLogs500


export function useGetActivityLogsSuspense<TData = Awaited<ReturnType<typeof getActivityLogs>>, TError = GetActivityLogs401 | GetActivityLogs403 | GetActivityLogs404 | GetActivityLogs500>(
 workspaceId: string,
    params: undefined |  GetActivityLogsParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getActivityLogs>>, TError, TData>>, request?: SecondParameter<typeof fetchWithAuth>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetActivityLogsSuspense<TData = Awaited<ReturnType<typeof getActivityLogs>>, TError = GetActivityLogs401 | GetActivityLogs403 | GetActivityLogs404 | GetActivityLogs500>(
 workspaceId: string,
    params?: GetActivityLogsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getActivityLogs>>, TError, TData>>, request?: SecondParameter<typeof fetchWithAuth>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetActivityLogsSuspense<TData = Awaited<ReturnType<typeof getActivityLogs>>, TError = GetActivityLogs401 | GetActivityLogs403 | GetActivityLogs404 | GetActivityLogs500>(
 workspaceId: string,
    params?: GetActivityLogsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getActivityLogs>>, TError, TData>>, request?: SecondParameter<typeof fetchWithAuth>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Activity Logs
 */

export function useGetActivityLogsSuspense<TData = Awaited<ReturnType<typeof getActivityLogs>>, TError = GetActivityLogs401 | GetActivityLogs403 | GetActivityLogs404 | GetActivityLogs500>(
 workspaceId: string,
    params?: GetActivityLogsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getActivityLogs>>, TError, TData>>, request?: SecondParameter<typeof fetchWithAuth>}
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetActivityLogsSuspenseQueryOptions(workspaceId,params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




