/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Rootly API
 * OpenAPI spec version: 0.1.0
 */

import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query'
import { useMutation } from '@tanstack/react-query'
import { fetchWithAuth } from '../../shared/lib/fetch'
import type {
  CreateWorkspace201,
  CreateWorkspace500,
  CreateWorkspaceBody,
} from '../model'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Create a new workspace
 * @summary Create Workspace
 */
export type createWorkspaceResponse201 = {
  data: CreateWorkspace201
  status: 201
}

export type createWorkspaceResponse500 = {
  data: CreateWorkspace500
  status: 500
}

export type createWorkspaceResponseSuccess = createWorkspaceResponse201 & {
  headers: Headers
}
export type createWorkspaceResponseError = createWorkspaceResponse500 & {
  headers: Headers
}

export type createWorkspaceResponse =
  | createWorkspaceResponseSuccess
  | createWorkspaceResponseError

export const getCreateWorkspaceUrl = () => {
  return `http://localhost:3333/api/workspaces`
}

export const createWorkspace = async (
  createWorkspaceBody: CreateWorkspaceBody,
  options?: RequestInit,
): Promise<createWorkspaceResponse> => {
  return fetchWithAuth<createWorkspaceResponse>(getCreateWorkspaceUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createWorkspaceBody),
  })
}

export const getCreateWorkspaceMutationOptions = <
  TError = CreateWorkspace500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createWorkspace>>,
    TError,
    { data: CreateWorkspaceBody },
    TContext
  >
  request?: SecondParameter<typeof fetchWithAuth>
}): UseMutationOptions<
  Awaited<ReturnType<typeof createWorkspace>>,
  TError,
  { data: CreateWorkspaceBody },
  TContext
> => {
  const mutationKey = ['createWorkspace']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createWorkspace>>,
    { data: CreateWorkspaceBody }
  > = (props) => {
    const { data } = props ?? {}

    return createWorkspace(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CreateWorkspaceMutationResult = NonNullable<
  Awaited<ReturnType<typeof createWorkspace>>
>
export type CreateWorkspaceMutationBody = CreateWorkspaceBody
export type CreateWorkspaceMutationError = CreateWorkspace500

/**
 * @summary Create Workspace
 */
export const useCreateWorkspace = <
  TError = CreateWorkspace500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createWorkspace>>,
      TError,
      { data: CreateWorkspaceBody },
      TContext
    >
    request?: SecondParameter<typeof fetchWithAuth>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createWorkspace>>,
  TError,
  { data: CreateWorkspaceBody },
  TContext
> => {
  return useMutation(getCreateWorkspaceMutationOptions(options), queryClient)
}
