/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Rootly API
 * OpenAPI spec version: 0.1.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query'
import { useQuery, useSuspenseQuery } from '@tanstack/react-query'
import { fetchWithAuth } from '../../shared/lib/fetch'
import type { GetMe200, GetMe401, GetMe500 } from '../model'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Get the authenticated user information
 * @summary Get Me
 */
export type getMeResponse200 = {
  data: GetMe200
  status: 200
}

export type getMeResponse401 = {
  data: GetMe401
  status: 401
}

export type getMeResponse500 = {
  data: GetMe500
  status: 500
}

export type getMeResponseSuccess = getMeResponse200 & {
  headers: Headers
}
export type getMeResponseError = (getMeResponse401 | getMeResponse500) & {
  headers: Headers
}

export type getMeResponse = getMeResponseSuccess | getMeResponseError

export const getGetMeUrl = () => {
  return `http://localhost:3333/api/me`
}

export const getMe = async (options?: RequestInit): Promise<getMeResponse> => {
  return fetchWithAuth<getMeResponse>(getGetMeUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getGetMeQueryKey = () => {
  return [`http://localhost:3333/api/me`] as const
}

export const getGetMeQueryOptions = <
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = GetMe401 | GetMe500,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>
  >
  request?: SecondParameter<typeof fetchWithAuth>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetMeQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({
    signal,
  }) => getMe({ signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMe>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>
export type GetMeQueryError = GetMe401 | GetMe500

export function useGetMe<
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = GetMe401 | GetMe500,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof fetchWithAuth>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetMe<
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = GetMe401 | GetMe500,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof fetchWithAuth>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetMe<
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = GetMe401 | GetMe500,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>
    >
    request?: SecondParameter<typeof fetchWithAuth>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get Me
 */

export function useGetMe<
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = GetMe401 | GetMe500,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>
    >
    request?: SecondParameter<typeof fetchWithAuth>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export const getGetMeSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = GetMe401 | GetMe500,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>
  >
  request?: SecondParameter<typeof fetchWithAuth>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetMeQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({
    signal,
  }) => getMe({ signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getMe>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMeSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMe>>
>
export type GetMeSuspenseQueryError = GetMe401 | GetMe500

export function useGetMeSuspense<
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = GetMe401 | GetMe500,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>
    >
    request?: SecondParameter<typeof fetchWithAuth>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetMeSuspense<
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = GetMe401 | GetMe500,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>
    >
    request?: SecondParameter<typeof fetchWithAuth>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetMeSuspense<
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = GetMe401 | GetMe500,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>
    >
    request?: SecondParameter<typeof fetchWithAuth>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get Me
 */

export function useGetMeSuspense<
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = GetMe401 | GetMe500,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>
    >
    request?: SecondParameter<typeof fetchWithAuth>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetMeSuspenseQueryOptions(options)

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}
