/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Rootly API
 * OpenAPI spec version: 0.1.0
 */
import { useQuery, useSuspenseQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query'

import type {
  GetWorkspaceMembers200,
  GetWorkspaceMembers401,
  GetWorkspaceMembers404,
  GetWorkspaceMembers500,
} from '../model'

import { fetchWithAuth } from '../../lib/fetch'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * List all members of a workspace with their user and role
 * @summary Get Workspace Members
 */
export type getWorkspaceMembersResponse200 = {
  data: GetWorkspaceMembers200
  status: 200
}

export type getWorkspaceMembersResponse401 = {
  data: GetWorkspaceMembers401
  status: 401
}

export type getWorkspaceMembersResponse404 = {
  data: GetWorkspaceMembers404
  status: 404
}

export type getWorkspaceMembersResponse500 = {
  data: GetWorkspaceMembers500
  status: 500
}

export type getWorkspaceMembersResponseSuccess =
  getWorkspaceMembersResponse200 & {
    headers: Headers
  }
export type getWorkspaceMembersResponseError = (
  | getWorkspaceMembersResponse401
  | getWorkspaceMembersResponse404
  | getWorkspaceMembersResponse500
) & {
  headers: Headers
}

export type getWorkspaceMembersResponse =
  | getWorkspaceMembersResponseSuccess
  | getWorkspaceMembersResponseError

export const getGetWorkspaceMembersUrl = (workspaceId: string) => {
  return `http://localhost:3333/api/workspaces/${workspaceId}/members`
}

export const getWorkspaceMembers = async (
  workspaceId: string,
  options?: RequestInit,
): Promise<getWorkspaceMembersResponse> => {
  return fetchWithAuth<getWorkspaceMembersResponse>(
    getGetWorkspaceMembersUrl(workspaceId),
    {
      ...options,
      method: 'GET',
    },
  )
}

export const getGetWorkspaceMembersQueryKey = (workspaceId: string) => {
  return [
    'http:',
    'localhost:3333',
    'api',
    'workspaces',
    workspaceId,
    'members',
  ] as const
}

export const getGetWorkspaceMembersQueryOptions = <
  TData = Awaited<ReturnType<typeof getWorkspaceMembers>>,
  TError =
    | GetWorkspaceMembers401
    | GetWorkspaceMembers404
    | GetWorkspaceMembers500,
>(
  workspaceId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWorkspaceMembers>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof fetchWithAuth>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getGetWorkspaceMembersQueryKey(workspaceId)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getWorkspaceMembers>>
  > = ({ signal }) =>
    getWorkspaceMembers(workspaceId, { signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    enabled: !!workspaceId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getWorkspaceMembers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetWorkspaceMembersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getWorkspaceMembers>>
>
export type GetWorkspaceMembersQueryError =
  | GetWorkspaceMembers401
  | GetWorkspaceMembers404
  | GetWorkspaceMembers500

export function useGetWorkspaceMembers<
  TData = Awaited<ReturnType<typeof getWorkspaceMembers>>,
  TError =
    | GetWorkspaceMembers401
    | GetWorkspaceMembers404
    | GetWorkspaceMembers500,
>(
  workspaceId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWorkspaceMembers>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkspaceMembers>>,
          TError,
          Awaited<ReturnType<typeof getWorkspaceMembers>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof fetchWithAuth>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetWorkspaceMembers<
  TData = Awaited<ReturnType<typeof getWorkspaceMembers>>,
  TError =
    | GetWorkspaceMembers401
    | GetWorkspaceMembers404
    | GetWorkspaceMembers500,
>(
  workspaceId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWorkspaceMembers>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkspaceMembers>>,
          TError,
          Awaited<ReturnType<typeof getWorkspaceMembers>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof fetchWithAuth>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetWorkspaceMembers<
  TData = Awaited<ReturnType<typeof getWorkspaceMembers>>,
  TError =
    | GetWorkspaceMembers401
    | GetWorkspaceMembers404
    | GetWorkspaceMembers500,
>(
  workspaceId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWorkspaceMembers>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof fetchWithAuth>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get Workspace Members
 */

export function useGetWorkspaceMembers<
  TData = Awaited<ReturnType<typeof getWorkspaceMembers>>,
  TError =
    | GetWorkspaceMembers401
    | GetWorkspaceMembers404
    | GetWorkspaceMembers500,
>(
  workspaceId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWorkspaceMembers>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof fetchWithAuth>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetWorkspaceMembersQueryOptions(workspaceId, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export const getGetWorkspaceMembersSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getWorkspaceMembers>>,
  TError =
    | GetWorkspaceMembers401
    | GetWorkspaceMembers404
    | GetWorkspaceMembers500,
>(
  workspaceId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getWorkspaceMembers>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof fetchWithAuth>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getGetWorkspaceMembersQueryKey(workspaceId)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getWorkspaceMembers>>
  > = ({ signal }) =>
    getWorkspaceMembers(workspaceId, { signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getWorkspaceMembers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetWorkspaceMembersSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getWorkspaceMembers>>
>
export type GetWorkspaceMembersSuspenseQueryError =
  | GetWorkspaceMembers401
  | GetWorkspaceMembers404
  | GetWorkspaceMembers500

export function useGetWorkspaceMembersSuspense<
  TData = Awaited<ReturnType<typeof getWorkspaceMembers>>,
  TError =
    | GetWorkspaceMembers401
    | GetWorkspaceMembers404
    | GetWorkspaceMembers500,
>(
  workspaceId: string,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getWorkspaceMembers>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof fetchWithAuth>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetWorkspaceMembersSuspense<
  TData = Awaited<ReturnType<typeof getWorkspaceMembers>>,
  TError =
    | GetWorkspaceMembers401
    | GetWorkspaceMembers404
    | GetWorkspaceMembers500,
>(
  workspaceId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getWorkspaceMembers>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof fetchWithAuth>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetWorkspaceMembersSuspense<
  TData = Awaited<ReturnType<typeof getWorkspaceMembers>>,
  TError =
    | GetWorkspaceMembers401
    | GetWorkspaceMembers404
    | GetWorkspaceMembers500,
>(
  workspaceId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getWorkspaceMembers>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof fetchWithAuth>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get Workspace Members
 */

export function useGetWorkspaceMembersSuspense<
  TData = Awaited<ReturnType<typeof getWorkspaceMembers>>,
  TError =
    | GetWorkspaceMembers401
    | GetWorkspaceMembers404
    | GetWorkspaceMembers500,
>(
  workspaceId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getWorkspaceMembers>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof fetchWithAuth>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetWorkspaceMembersSuspenseQueryOptions(
    workspaceId,
    options,
  )

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}
