/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Rootly API
 * OpenAPI spec version: 0.1.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query'
import { useMutation, useQuery, useSuspenseQuery } from '@tanstack/react-query'
import { fetchWithAuth } from '../../lib/fetch'
import type {
  CreateWsTicket201,
  CreateWsTicket401,
  CreateWsTicket500,
  GetNotifications200,
  GetNotifications401,
  GetNotifications500,
  ReadNotification401,
  ReadNotification403,
  ReadNotification404,
  ReadNotification500,
} from '../model'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * List the authenticated user notifications
 * @summary Get Notifications
 */
export type getNotificationsResponse200 = {
  data: GetNotifications200
  status: 200
}

export type getNotificationsResponse401 = {
  data: GetNotifications401
  status: 401
}

export type getNotificationsResponse500 = {
  data: GetNotifications500
  status: 500
}

export type getNotificationsResponseSuccess = getNotificationsResponse200 & {
  headers: Headers
}
export type getNotificationsResponseError = (
  | getNotificationsResponse401
  | getNotificationsResponse500
) & {
  headers: Headers
}

export type getNotificationsResponse =
  | getNotificationsResponseSuccess
  | getNotificationsResponseError

export const getGetNotificationsUrl = () => {
  return `http://localhost:3333/api/notifications`
}

export const getNotifications = async (
  options?: RequestInit,
): Promise<getNotificationsResponse> => {
  return fetchWithAuth<getNotificationsResponse>(getGetNotificationsUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getGetNotificationsQueryKey = () => {
  return ['http:', 'localhost:3333', 'api', 'notifications'] as const
}

export const getGetNotificationsQueryOptions = <
  TData = Awaited<ReturnType<typeof getNotifications>>,
  TError = GetNotifications401 | GetNotifications500,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getNotifications>>, TError, TData>
  >
  request?: SecondParameter<typeof fetchWithAuth>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetNotificationsQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getNotifications>>
  > = ({ signal }) => getNotifications({ signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getNotifications>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetNotificationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getNotifications>>
>
export type GetNotificationsQueryError =
  | GetNotifications401
  | GetNotifications500

export function useGetNotifications<
  TData = Awaited<ReturnType<typeof getNotifications>>,
  TError = GetNotifications401 | GetNotifications500,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getNotifications>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNotifications>>,
          TError,
          Awaited<ReturnType<typeof getNotifications>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof fetchWithAuth>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetNotifications<
  TData = Awaited<ReturnType<typeof getNotifications>>,
  TError = GetNotifications401 | GetNotifications500,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getNotifications>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNotifications>>,
          TError,
          Awaited<ReturnType<typeof getNotifications>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof fetchWithAuth>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetNotifications<
  TData = Awaited<ReturnType<typeof getNotifications>>,
  TError = GetNotifications401 | GetNotifications500,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getNotifications>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof fetchWithAuth>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get Notifications
 */

export function useGetNotifications<
  TData = Awaited<ReturnType<typeof getNotifications>>,
  TError = GetNotifications401 | GetNotifications500,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getNotifications>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof fetchWithAuth>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetNotificationsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export const getGetNotificationsSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getNotifications>>,
  TError = GetNotifications401 | GetNotifications500,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getNotifications>>,
      TError,
      TData
    >
  >
  request?: SecondParameter<typeof fetchWithAuth>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetNotificationsQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getNotifications>>
  > = ({ signal }) => getNotifications({ signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getNotifications>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetNotificationsSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getNotifications>>
>
export type GetNotificationsSuspenseQueryError =
  | GetNotifications401
  | GetNotifications500

export function useGetNotificationsSuspense<
  TData = Awaited<ReturnType<typeof getNotifications>>,
  TError = GetNotifications401 | GetNotifications500,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getNotifications>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof fetchWithAuth>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetNotificationsSuspense<
  TData = Awaited<ReturnType<typeof getNotifications>>,
  TError = GetNotifications401 | GetNotifications500,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getNotifications>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof fetchWithAuth>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetNotificationsSuspense<
  TData = Awaited<ReturnType<typeof getNotifications>>,
  TError = GetNotifications401 | GetNotifications500,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getNotifications>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof fetchWithAuth>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get Notifications
 */

export function useGetNotificationsSuspense<
  TData = Awaited<ReturnType<typeof getNotifications>>,
  TError = GetNotifications401 | GetNotifications500,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getNotifications>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof fetchWithAuth>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetNotificationsSuspenseQueryOptions(options)

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * Mark a notification as read
 * @summary Read Notification
 */
export type readNotificationResponse204 = {
  data: void
  status: 204
}

export type readNotificationResponse401 = {
  data: ReadNotification401
  status: 401
}

export type readNotificationResponse403 = {
  data: ReadNotification403
  status: 403
}

export type readNotificationResponse404 = {
  data: ReadNotification404
  status: 404
}

export type readNotificationResponse500 = {
  data: ReadNotification500
  status: 500
}

export type readNotificationResponseSuccess = readNotificationResponse204 & {
  headers: Headers
}
export type readNotificationResponseError = (
  | readNotificationResponse401
  | readNotificationResponse403
  | readNotificationResponse404
  | readNotificationResponse500
) & {
  headers: Headers
}

export type readNotificationResponse =
  | readNotificationResponseSuccess
  | readNotificationResponseError

export const getReadNotificationUrl = (notificationId: string) => {
  return `http://localhost:3333/api/notifications/${notificationId}/read`
}

export const readNotification = async (
  notificationId: string,
  options?: RequestInit,
): Promise<readNotificationResponse> => {
  return fetchWithAuth<readNotificationResponse>(
    getReadNotificationUrl(notificationId),
    {
      ...options,
      method: 'PATCH',
    },
  )
}

export const getReadNotificationMutationOptions = <
  TError =
    | ReadNotification401
    | ReadNotification403
    | ReadNotification404
    | ReadNotification500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof readNotification>>,
    TError,
    { notificationId: string },
    TContext
  >
  request?: SecondParameter<typeof fetchWithAuth>
}): UseMutationOptions<
  Awaited<ReturnType<typeof readNotification>>,
  TError,
  { notificationId: string },
  TContext
> => {
  const mutationKey = ['readNotification']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof readNotification>>,
    { notificationId: string }
  > = (props) => {
    const { notificationId } = props ?? {}

    return readNotification(notificationId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ReadNotificationMutationResult = NonNullable<
  Awaited<ReturnType<typeof readNotification>>
>

export type ReadNotificationMutationError =
  | ReadNotification401
  | ReadNotification403
  | ReadNotification404
  | ReadNotification500

/**
 * @summary Read Notification
 */
export const useReadNotification = <
  TError =
    | ReadNotification401
    | ReadNotification403
    | ReadNotification404
    | ReadNotification500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof readNotification>>,
      TError,
      { notificationId: string },
      TContext
    >
    request?: SecondParameter<typeof fetchWithAuth>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof readNotification>>,
  TError,
  { notificationId: string },
  TContext
> => {
  return useMutation(getReadNotificationMutationOptions(options), queryClient)
}
/**
 * Issue a short-lived ticket used to authenticate a WebSocket connection
 * @summary Create WebSocket Ticket
 */
export type createWsTicketResponse201 = {
  data: CreateWsTicket201
  status: 201
}

export type createWsTicketResponse401 = {
  data: CreateWsTicket401
  status: 401
}

export type createWsTicketResponse500 = {
  data: CreateWsTicket500
  status: 500
}

export type createWsTicketResponseSuccess = createWsTicketResponse201 & {
  headers: Headers
}
export type createWsTicketResponseError = (
  | createWsTicketResponse401
  | createWsTicketResponse500
) & {
  headers: Headers
}

export type createWsTicketResponse =
  | createWsTicketResponseSuccess
  | createWsTicketResponseError

export const getCreateWsTicketUrl = () => {
  return `http://localhost:3333/api/ws-ticket`
}

export const createWsTicket = async (
  options?: RequestInit,
): Promise<createWsTicketResponse> => {
  return fetchWithAuth<createWsTicketResponse>(getCreateWsTicketUrl(), {
    ...options,
    method: 'POST',
  })
}

export const getCreateWsTicketMutationOptions = <
  TError = CreateWsTicket401 | CreateWsTicket500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createWsTicket>>,
    TError,
    void,
    TContext
  >
  request?: SecondParameter<typeof fetchWithAuth>
}): UseMutationOptions<
  Awaited<ReturnType<typeof createWsTicket>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['createWsTicket']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createWsTicket>>,
    void
  > = () => {
    return createWsTicket(requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CreateWsTicketMutationResult = NonNullable<
  Awaited<ReturnType<typeof createWsTicket>>
>

export type CreateWsTicketMutationError = CreateWsTicket401 | CreateWsTicket500

/**
 * @summary Create WebSocket Ticket
 */
export const useCreateWsTicket = <
  TError = CreateWsTicket401 | CreateWsTicket500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createWsTicket>>,
      TError,
      void,
      TContext
    >
    request?: SecondParameter<typeof fetchWithAuth>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createWsTicket>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getCreateWsTicketMutationOptions(options), queryClient)
}
